MFiX-Exa: mfix/src/des/calc_particle_collisions.f90 File Reference
calc_particle_collisions.f90 File Reference
Functions/Subroutines
subroutine calc_particle_collisions (rparticles, nrp, gparticles, ngp, nbor_list, size_nl, tow, fc, dtsolid, ncoll)
Function/Subroutine Documentation
subroutine calc_particle_collisions (type(particle_t), dimension(nrp), intent(in) rparticles, integer, intent(in) nrp, type(particle_t), dimension(ngp), intent(in) gparticles, integer, intent(in) ngp, integer, dimension(size_nl), intent(in) nbor_list, integer, intent(in) size_nl, real(rt), dimension(nrp+ngp,3), intent(inout) tow, real(rt), dimension(nrp+ngp,3), intent(inout) fc, real(rt), intent(in) dtsolid, integer(c_int), intent(inout) ncoll)
References cfrelvel_module::cfrelvel(), discretelement::des_crossprdct(), discretelement::des_etan, discretelement::des_etat, dot_product(), discretelement::kn, discretelement::kt, and discretelement::mew.
Referenced by MFIXParticleContainer::EvolveParticles().