MFiX-Exa: par_gen_module Module Reference
par_gen_module Module Reference
Public Member Functions
subroutine particle_generator (pc, lo, hi, dx, dy, dz)
subroutine hex_close_pack (icv, type, lo, hi, np, pc, dx, dy, dz)
subroutine random_fill (icv, type, lo, hi, np, pc, dx, dy, dz)
subroutine mfix_particle_generator_prop (nrp, particles)
subroutine nor_rno (dp, mean, sigma, dp_min, dp_max)
subroutine uni_rno (dp, dp_min, dp_max)
subroutine init_random_seed
subroutine grow_pdata (gsize)
subroutine particle_write (nrp, particles)
subroutine rm_wall_collisions (particles, nrp, valid, vlo, vhi, phi, phlo, phhi, dx, n_refine)
Public Attributes
real(rt), dimension(:,:),
allocatable rdata
integer, dimension(:,:),
allocatable idata
Position............... 1,2,3 Radius................. 4 Density................ 5 Linear velocity........ 6,7,8.
integer, parameter nr = 8
Type................... 1.
integer, parameter ni = 1
Member Function/Subroutine Documentation
subroutine par_gen_module::grow_pdata (integer, intent(in) gsize)
Referenced by hex_close_pack(), and random_fill().
subroutine par_gen_module::hex_close_pack (integer(c_int), intent(in) icv, integer(c_int), intent(in) type, integer(c_int), dimension(3), intent(in) lo, integer(c_int), dimension(3), intent(in) hi, integer(c_int), intent(inout) np, integer(c_int), intent(inout) pc, real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz)
References calc_cell_module::calc_cell_ic(), and grow_pdata().
Referenced by particle_generator().
subroutine par_gen_module::init_random_seed ()
subroutine par_gen_module::mfix_particle_generator_prop (integer(c_int), intent(in) nrp, type(particle_t), dimension(nrp), intent(inout) particles)
subroutine par_gen_module::nor_rno (real(rt), dimension(:), intent(inout) dp, real(rt), intent(in) mean, real(rt), intent(in) sigma, real(rt), intent(in) dp_min, real(rt), intent(in) dp_max)
Referenced by particle_generator().
subroutine par_gen_module::particle_generator (integer(c_int), intent(inout) pc, integer(c_int), dimension(3), intent(in) lo, integer(c_int), dimension(3), intent(in) hi, real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz)
References hex_close_pack(), nor_rno(), random_fill(), and uni_rno().
subroutine par_gen_module::particle_write (integer(c_int), intent(in) nrp, type(particle_t), dimension(nrp), intent(in) particles)
subroutine par_gen_module::random_fill (integer(c_int), intent(in) icv, integer(c_int), intent(in) type, integer(c_int), dimension(3), intent(in) lo, integer(c_int), dimension(3), intent(in) hi, integer(c_int), intent(inout) np, integer(c_int), intent(inout) pc, real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz)
References calc_cell_module::calc_cell_ic(), and grow_pdata().
Referenced by particle_generator().
subroutine par_gen_module::rm_wall_collisions (type(particle_t), dimension(nrp), intent(inout), target particles, integer, intent(in) nrp, integer, dimension(vlo(1): vhi(1), vlo(2): vhi(2), vlo(3): vhi(3)), intent(in) valid, integer, dimension(3), intent(in) vlo, integer, dimension(3), intent(in) vhi, real(rt), dimension(phlo(1):phhi(1), phlo(2):phhi(2), phlo(3):phhi(3)), intent(in) phi, integer, dimension(3), intent(in) phlo, integer, dimension(3), intent(in) phhi, real(rt), dimension (3), intent(in) dx, integer, intent(in) n_refine)
subroutine par_gen_module::uni_rno (real(rt), dimension(:), intent(inout) dp, real(rt), intent(in) dp_min, real(rt), intent(in) dp_max)
Referenced by particle_generator().
Member Data Documentation
integer, dimension(:,:), allocatable par_gen_module::idata
Position............... 1,2,3 Radius................. 4 Density................ 5 Linear velocity........ 6,7,8.
integer, parameter par_gen_module::ni = 1
integer, parameter par_gen_module::nr = 8
Type................... 1.
real(rt), dimension(:,:), allocatable par_gen_module::rdata
The documentation for this module was generated from the following file:
mfix/src/des/particle_generator.f90