MFiX-Exa: check_bc_flow_module Module Reference
check_bc_flow_module Module Reference
Public Member Functions
subroutine, public check_bc_flow ()
subroutine check_bc_vel_inflow (check, bcv)
subroutine check_bc_vel_outflow (check, bcv)
Member Function/Subroutine Documentation
subroutine, public check_bc_flow_module::check_bc_flow ()
References bc::bc_defined(), check_bc_vel_inflow(), and check_bc_vel_outflow().
subroutine check_bc_flow_module::check_bc_vel_inflow (logical, dimension(dim_m), intent(in) check, integer, intent(in) bcv)
References error_manager::finl_err_msg(), error_manager::flush_err_msg(), error_manager::init_err_msg(), and error_manager::ivar().
Referenced by check_bc_flow().
subroutine check_bc_flow_module::check_bc_vel_outflow (logical, dimension(dim_m), intent(in) check, integer, intent(in) bcv)
References error_manager::finl_err_msg(), error_manager::flush_err_msg(), error_manager::init_err_msg(), and error_manager::ivar().
Referenced by check_bc_flow().
The documentation for this module was generated from the following file:
mfix/src/check_data/check_bc_flow.f90