MFiX-Exa: bc Module Reference
bc Module Reference
Public Member Functions
subroutine set_cyclic (cyc_x, cyc_y, cyc_z)
logical function bc_defined (icv)
subroutine write_out_bc (unit_out, dx, dy, dz, xlength, ylength, zlength, domlo, domhi)
Public Attributes
character(len=16), dimension(dim_bc) bc_type
logical cyclic_x = .false.
logical cyclic_y = .false.
logical cyclic_z = .false.
real(c_real), dimension(dim_bc) bc_x_w
real(c_real), dimension(dim_bc) bc_x_e
real(c_real), dimension(dim_bc) bc_y_s
real(c_real), dimension(dim_bc) bc_y_n
real(c_real), dimension(dim_bc) bc_z_b
real(c_real), dimension(dim_bc) bc_z_t
real(c_real), dimension(dim_bc) bc_ep_g
real(c_real), dimension(dim_bc,
dim_m) bc_ep_s
real(c_real), dimension(dim_bc) bc_p_g
real(c_real), dimension(dim_bc) bc_u_g
real(c_real), dimension(dim_bc,
dim_m) bc_u_s
real(c_real), dimension(dim_bc) bc_v_g
real(c_real), dimension(dim_bc,
dim_m) bc_v_s
real(c_real), dimension(dim_bc) bc_w_g
real(c_real), dimension(dim_bc,
dim_m) bc_w_s
real(c_real), dimension(dim_bc) bc_volflow_g
real(c_real), dimension(dim_bc,
dim_m) bc_volflow_s
real(c_real), dimension(dim_bc) bc_massflow_g
real(c_real), dimension(dim_bc,
dim_m) bc_massflow_s
real(c_real) delp_x
real(c_real) delp_y
real(c_real) delp_z
real(c_real), dimension(dim_bc) bc_hw_g
real(c_real), dimension(dim_bc) bc_uw_g
real(c_real), dimension(dim_bc) bc_vw_g
real(c_real), dimension(dim_bc) bc_ww_g
real(c_real), dimension(dim_bc) bc_t_g
real(c_real), dimension(dim_bc,
dim_m) bc_t_s
real(c_real), dimension(dim_bc) bc_hw_t_g
real(c_real), dimension(dim_bc,
dim_m) bc_hw_t_s
real(c_real), dimension(dim_bc) bc_tw_g
real(c_real), dimension(dim_bc,
dim_m) bc_tw_s
real(c_real), dimension(dim_bc) bc_c_t_g
real(c_real), dimension(dim_bc,
dim_m) bc_c_t_s
real(c_real), dimension(dim_bc,
dim_n_g) bc_x_g
real(c_real), dimension(dim_bc,
dim_m, dim_n_s) bc_x_s
real(c_real), dimension(dim_bc,
dim_n_g) bc_hw_x_g
real(c_real), dimension(dim_bc,
dim_n_g) bc_xw_g
real(c_real), dimension(dim_bc,
dim_n_g) bc_c_x_g
character, dimension(dim_bc) bc_plane
integer, parameter undef_cell = 0
integer, parameter pinf_ = 10
integer, parameter pout_ = 11
integer, parameter minf_ = 20
integer, parameter nsw_ = 100
integer, parameter fsw_ = 101
integer, parameter psw_ = 102
integer, parameter cycl_ = 50
integer, parameter cycp_ = 51
Member Function/Subroutine Documentation
logical function bc::bc_defined (integer, intent(in) icv)
Referenced by check_bc_flow_module::check_bc_flow(), check_bc_geometry_module::check_bc_geometry(), check_boundary_conditions_module::check_boundary_conditions(), set_bc_flow_module::set_bc_flow(), set_bc_type_module::set_bc_type(), init_fluid_module::set_p_g(), and write_out_bc().
subroutine bc::set_cyclic (integer, intent(in) cyc_x, integer, intent(in) cyc_y, integer, intent(in) cyc_z)
subroutine bc::write_out_bc (integer, intent(in) unit_out, real(c_real), intent(in) dx, real(c_real), intent(in) dy, real(c_real), intent(in) dz, real(c_real), intent(in) xlength, real(c_real), intent(in) ylength, real(c_real), intent(in) zlength, integer(c_int), dimension(3), intent(in) domlo, integer(c_int), dimension(3), intent(in) domhi)
References bc_defined(), calc_cell_module::calc_cell_bc_flow(), and calc_cell_module::calc_cell_bc_wall().
Referenced by write_out0().
Member Data Documentation
real(c_real), dimension (dim_bc) bc::bc_c_t_g
real(c_real), dimension (dim_bc, dim_m) bc::bc_c_t_s
real(c_real), dimension (dim_bc, dim_n_g) bc::bc_c_x_g
real(c_real), dimension(dim_bc) bc::bc_ep_g
real(c_real), dimension(dim_bc, dim_m) bc::bc_ep_s
real(c_real), dimension(dim_bc) bc::bc_hw_g
real(c_real), dimension(dim_bc) bc::bc_hw_t_g
real(c_real), dimension(dim_bc, dim_m) bc::bc_hw_t_s
real(c_real), dimension(dim_bc, dim_n_g) bc::bc_hw_x_g
real(c_real), dimension(dim_bc) bc::bc_massflow_g
real(c_real), dimension(dim_bc, dim_m) bc::bc_massflow_s
real(c_real), dimension(dim_bc) bc::bc_p_g
character, dimension(dim_bc) bc::bc_plane
real(c_real), dimension (dim_bc) bc::bc_t_g
real(c_real), dimension (dim_bc, dim_m) bc::bc_t_s
real(c_real), dimension (dim_bc) bc::bc_tw_g
real(c_real), dimension (dim_bc, dim_m) bc::bc_tw_s
character(len=16), dimension(dim_bc) bc::bc_type
real(c_real), dimension(dim_bc) bc::bc_u_g
real(c_real), dimension(dim_bc, dim_m) bc::bc_u_s
real(c_real), dimension(dim_bc) bc::bc_uw_g
real(c_real), dimension(dim_bc) bc::bc_v_g
real(c_real), dimension(dim_bc, dim_m) bc::bc_v_s
real(c_real), dimension(dim_bc) bc::bc_volflow_g
real(c_real), dimension(dim_bc, dim_m) bc::bc_volflow_s
real(c_real), dimension(dim_bc) bc::bc_vw_g
real(c_real), dimension(dim_bc) bc::bc_w_g
real(c_real), dimension(dim_bc, dim_m) bc::bc_w_s
real(c_real), dimension(dim_bc) bc::bc_ww_g
real(c_real), dimension(dim_bc) bc::bc_x_e
real(c_real), dimension(dim_bc, dim_n_g) bc::bc_x_g
real(c_real), dimension(dim_bc, dim_m, dim_n_s) bc::bc_x_s
real(c_real), dimension(dim_bc) bc::bc_x_w
real(c_real), dimension (dim_bc, dim_n_g) bc::bc_xw_g
real(c_real), dimension(dim_bc) bc::bc_y_n
real(c_real), dimension(dim_bc) bc::bc_y_s
real(c_real), dimension(dim_bc) bc::bc_z_b
real(c_real), dimension(dim_bc) bc::bc_z_t
integer, parameter bc::cycl_ = 50
logical bc::cyclic_x = .false.
logical bc::cyclic_y = .false.
logical bc::cyclic_z = .false.
integer, parameter bc::cycp_ = 51
real(c_real) bc::delp_x
real(c_real) bc::delp_y
real(c_real) bc::delp_z
integer, parameter bc::fsw_ = 101
integer, parameter bc::minf_ = 20
integer, parameter bc::nsw_ = 100
integer, parameter bc::pinf_ = 10
integer, parameter bc::pout_ = 11
integer, parameter bc::psw_ = 102
integer, parameter bc::undef_cell = 0
The documentation for this module was generated from the following file:
mfix/src/bc_mod.f90