MFiX-Exa: source_w_g_module Module Reference
source_w_g_module Module Reference
Public Member Functions
subroutine source_w_g (lo, hi, slo, shi, wlo, whi, alo, ahi, dlo, dhi, A_m, b_m, p_g, p0_g, ep_g, ro_g, rop_go, w_go, tau_w_g, f_gds_w, drag_w, dt, dx, dy, dz, domlo, domhi)
subroutine source_w_g_bc (lo, hi, slo, shi, alo, ahi, A_m, b_m, bc_ilo_type, bc_ihi_type, bc_jlo_type, bc_jhi_type, bc_klo_type, bc_khi_type, domlo, domhi, ng, dx, dy)
subroutine point_source_w_g (lo, hi, alo, ahi, b_m, vol)
Member Function/Subroutine Documentation
subroutine source_w_g_module::point_source_w_g (integer(c_int), dimension(3), intent(in) lo, integer(c_int), dimension(3), intent(in) hi, integer(c_int), dimension(3), intent(in) alo, integer(c_int), dimension(3), intent(in) ahi, real(rt), dimension(alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)), intent(inout) b_m, real(rt), intent(in) vol)
Referenced by solve_vel_star_module::solve_w_g_star().
subroutine source_w_g_module::source_w_g (integer, dimension(3), intent(in) lo, integer, dimension(3), intent(in) hi, integer, dimension(3), intent(in) slo, integer, dimension(3), intent(in) shi, integer, dimension(3), intent(in) wlo, integer, dimension(3), intent(in) whi, integer, dimension(3), intent(in) alo, integer, dimension(3), intent(in) ahi, integer, dimension(3), intent(in) dlo, integer, dimension(3), intent(in) dhi, real(rt), dimension(alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3),-3:3), intent(inout) A_m, real(rt), dimension(alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)), intent(inout) b_m, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) p_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) p0_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ep_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ro_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) rop_go, w_go, tau_w_g, f_gds_w, drag_w, real(rt), intent(in) dt, real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz, integer, dimension(3), intent(in) domlo, integer, dimension(3), intent(in) domhi)
Referenced by solve_vel_star_module::solve_w_g_star().
subroutine source_w_g_module::source_w_g_bc (integer, dimension(3), intent(in) lo, integer, dimension(3), intent(in) hi, integer, dimension(3), intent(in) slo, integer, dimension(3), intent(in) shi, integer, dimension(3), intent(in) alo, integer, dimension(3), intent(in) ahi, real(rt), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3),-3:3), intent(inout) A_m, real(rt), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)), intent(inout) b_m, integer(c_int), dimension(domlo(2)-ng:domhi(2)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_ilo_type, integer(c_int), dimension(domlo(2)-ng:domhi(2)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_ihi_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_jlo_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_jhi_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(2)-ng:domhi(2)+ng,2), intent(in) bc_klo_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(2)-ng:domhi(2)+ng,2), intent(in) bc_khi_type, integer, dimension(3), intent(in) domlo, integer, dimension(3), intent(in) domhi, integer, intent(in) ng, real(rt), intent(in) dx, real(rt), intent(in) dy)
Referenced by solve_vel_star_module::solve_w_g_star().
The documentation for this module was generated from the following file:
mfix/src/simple/source_w_g.f90