MFiX-Exa: calc_d_mod Module Reference
calc_d_mod Module Reference
Public Member Functions
subroutine calc_d_e (lo, hi, slo, shi, ulo, uhi, alo, ahi, d_e, A_m, ep_g, dy, dz, domlo, domhi, bc_ilo_type, bc_ihi_type)
subroutine calc_d_n (lo, hi, slo, shi, vlo, vhi, alo, ahi, d_n, A_m, ep_g, dx, dz, domlo, domhi, bc_jlo_type, bc_jhi_type)
subroutine calc_d_t (lo, hi, slo, shi, wlo, whi, alo, ahi, d_t, A_m, ep_g, dx, dy, domlo, domhi, bc_klo_type, bc_khi_type)
Member Function/Subroutine Documentation
subroutine calc_d_mod::calc_d_e (integer, dimension(3), intent(in) lo, integer, dimension(3), intent(in) hi, integer, dimension(3), intent(in) slo, integer, dimension(3), intent(in) shi, integer, dimension(3), intent(in) ulo, integer, dimension(3), intent(in) uhi, integer, dimension(3), intent(in) alo, integer, dimension(3), intent(in) ahi, real(c_real), dimension (ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(out) d_e, real(c_real), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3), -3:3), intent(in) A_m, real(c_real), dimension(slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ep_g, real(c_real), intent(in) dy, real(c_real), intent(in) dz, integer, dimension(3), intent(in) domlo, integer, dimension(3), intent(in) domhi, integer(c_int), dimension(domlo(2)-2:domhi(2)+2,domlo(3)-2:domhi(3)+2,2), intent(in) bc_ilo_type, integer(c_int), dimension(domlo(2)-2:domhi(2)+2,domlo(3)-2:domhi(3)+2,2), intent(in) bc_ihi_type)
Referenced by solve_vel_star_module::solve_u_g_star().
subroutine calc_d_mod::calc_d_n (integer, dimension(3), intent(in) lo, integer, dimension(3), intent(in) hi, integer, dimension(3), intent(in) slo, integer, dimension(3), intent(in) shi, integer, dimension(3), intent(in) vlo, integer, dimension(3), intent(in) vhi, integer, dimension(3), intent(in) alo, integer, dimension(3), intent(in) ahi, real(c_real), dimension (vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3)), intent(out) d_n, real(c_real), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3), -3:3), intent(in) A_m, real(c_real), dimension(slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ep_g, real(c_real), intent(in) dx, real(c_real), intent(in) dz, integer, dimension(3), intent(in) domlo, integer, dimension(3), intent(in) domhi, integer(c_int), dimension(domlo(1)-2:domhi(1)+2,domlo(3)-2:domhi(3)+2,2), intent(in) bc_jlo_type, integer(c_int), dimension(domlo(1)-2:domhi(1)+2,domlo(3)-2:domhi(3)+2,2), intent(in) bc_jhi_type)
Referenced by solve_vel_star_module::solve_v_g_star().
subroutine calc_d_mod::calc_d_t (integer, dimension(3), intent(in) lo, integer, dimension(3), intent(in) hi, integer, dimension(3), intent(in) slo, integer, dimension(3), intent(in) shi, integer, dimension(3), intent(in) wlo, integer, dimension(3), intent(in) whi, integer, dimension(3), intent(in) alo, integer, dimension(3), intent(in) ahi, real(c_real), dimension (wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3)), intent(out) d_t, real(c_real), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3), -3:3), intent(in) A_m, real(c_real), dimension(slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ep_g, real(c_real), intent(in) dx, real(c_real), intent(in) dy, integer, dimension(3), intent(in) domlo, integer, dimension(3), intent(in) domhi, integer(c_int), dimension(domlo(1)-2:domhi(1)+2,domlo(2)-2:domhi(2)+2,2), intent(in) bc_klo_type, integer(c_int), dimension(domlo(1)-2:domhi(1)+2,domlo(2)-2:domhi(2)+2,2), intent(in) bc_khi_type)
Referenced by solve_vel_star_module::solve_w_g_star().
The documentation for this module was generated from the following file:
mfix/src/calc_d.f90