MFiX-Exa: projection_mod Module Reference
projection_mod Module Reference
Public Member Functions
subroutine compute_fluid_acceleration (lo, hi, rhs, rlo, rhi, sl, u, ulo, uhi, v, vlo, vhi, w, wlo, whi, mu, slo, shi, ro, ep, trD, lambda, dx, dir, upw_ep)
subroutine add_grad_phi (lo, hi, u_i, ulo, uhi, ro_g, phi, slo, shi, dx, c, dir)
subroutine compute_intermediate_velocity (lo, hi, u_i, ulo, uhi, f_gds_i, flo, fhi, ro, slo, shi, ep, dir, dt, upw_ep)
Member Function/Subroutine Documentation
subroutine projection_mod::add_grad_phi (integer(c_int), dimension(3), intent(in) lo, integer(c_int), dimension(3), intent(in) hi, real(ar), dimension(ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(inout) u_i, integer(c_int), dimension(3), intent(in) ulo, integer(c_int), dimension(3), intent(in) uhi, real(ar), dimension(slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ro_g, real(ar), dimension(slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) phi, integer(c_int), dimension(3), intent(in) slo, integer(c_int), dimension(3), intent(in) shi, real(ar), dimension(3), intent(in) dx, real(ar), intent(in) c, integer(c_int), intent(in) dir)
subroutine projection_mod::compute_fluid_acceleration (integer(c_int), dimension(3), intent(in) lo, integer(c_int), dimension(3), intent(in) hi, real(ar), dimension(rlo(1):rhi(1),rlo(2):rhi(2),rlo(3):rhi(3)), intent(inout) rhs, integer(c_int), dimension(3), intent(in) rlo, integer(c_int), dimension(3), intent(in) rhi, real(ar), dimension(rlo(1):rhi(1),rlo(2):rhi(2),rlo(3):rhi(3)), intent(in) sl, real(ar), dimension(ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(in) u, integer(c_int), dimension(3), intent(in) ulo, integer(c_int), dimension(3), intent(in) uhi, real(ar), dimension(vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3)), intent(in) v, integer(c_int), dimension(3), intent(in) vlo, integer(c_int), dimension(3), intent(in) vhi, real(ar), dimension(wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3)), intent(in) w, integer(c_int), dimension(3), intent(in) wlo, integer(c_int), dimension(3), intent(in) whi, real(ar), dimension(slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) mu, integer(c_int), dimension(3), intent(in) slo, integer(c_int), dimension(3), intent(in) shi, real(ar), dimension(slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ro, real(ar), dimension(slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ep, real(ar), dimension(slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) trD, real(ar), dimension(slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) lambda, real(ar), dimension(3), intent(in) dx, integer(c_int), intent(in) dir, integer, intent(in) upw_ep)
References diffusion_mod::compute_divtau_x(), diffusion_mod::compute_divtau_y(), diffusion_mod::compute_divtau_z(), convection_mod::compute_ugradu_x(), convection_mod::compute_ugradu_y(), and convection_mod::compute_ugradu_z().
subroutine projection_mod::compute_intermediate_velocity (integer(c_int), dimension(3), intent(in) lo, integer(c_int), dimension(3), intent(in) hi, real(ar), dimension(ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(inout) u_i, integer(c_int), dimension(3), intent(in) ulo, integer(c_int), dimension(3), intent(in) uhi, real(ar), dimension(flo(1):fhi(1),flo(2):fhi(2),flo(3):fhi(3)), intent(in) f_gds_i, integer(c_int), dimension(3), intent(in) flo, integer(c_int), dimension(3), intent(in) fhi, real(ar), dimension(slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ro, integer(c_int), dimension(3), intent(in) slo, integer(c_int), dimension(3), intent(in) shi, real(ar), dimension(slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ep, integer(c_int), intent(in) dir, real(ar), intent(in) dt, integer, intent(in) upw_ep)
References get_bc_face().
The documentation for this module was generated from the following file:
mfix/src/projection/projection_mod.f90