MFiX-Exa: convection_mod Module Reference
convection_mod Module Reference
Public Member Functions
subroutine, public compute_ugradu_x (lo, hi, ug, ulo, uhi, vg, vlo, vhi, wg, wlo, whi, slopes, ugradu_x, dx)
subroutine, public compute_ugradu_y (lo, hi, ug, ulo, uhi, vg, vlo, vhi, wg, wlo, whi, slopes, ugradu_y, dx)
subroutine, public compute_ugradu_z (lo, hi, ug, ulo, uhi, vg, vlo, vhi, wg, wlo, whi, slopes, ugradu_z, dx)
Member Function/Subroutine Documentation
subroutine, public convection_mod::compute_ugradu_x (integer(c_int), dimension(3), intent(in) lo, integer(c_int), dimension(3), intent(in) hi, real(ar), dimension(ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(in) ug, integer(c_int), dimension(3), intent(in) ulo, integer(c_int), dimension(3), intent(in) uhi, real(ar), dimension(vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3)), intent(in) vg, integer(c_int), dimension(3), intent(in) vlo, integer(c_int), dimension(3), intent(in) vhi, real(ar), dimension(wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3)), intent(in) wg, integer(c_int), dimension(3), intent(in) wlo, integer(c_int), dimension(3), intent(in) whi, real(ar), dimension(ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3),3), intent(in) slopes, real(ar), dimension(ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(out) ugradu_x, real(ar), dimension(3), intent(in) dx)
Referenced by projection_mod::compute_fluid_acceleration().
subroutine, public convection_mod::compute_ugradu_y (integer(c_int), dimension(3), intent(in) lo, integer(c_int), dimension(3), intent(in) hi, real(ar), dimension(ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(in) ug, integer(c_int), dimension(3), intent(in) ulo, integer(c_int), dimension(3), intent(in) uhi, real(ar), dimension(vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3)), intent(in) vg, integer(c_int), dimension(3), intent(in) vlo, integer(c_int), dimension(3), intent(in) vhi, real(ar), dimension(wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3)), intent(in) wg, integer(c_int), dimension(3), intent(in) wlo, integer(c_int), dimension(3), intent(in) whi, real(ar), dimension(vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3),3), intent(in) slopes, real(ar), dimension(vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3)), intent(out) ugradu_y, real(ar), dimension(3), intent(in) dx)
Referenced by projection_mod::compute_fluid_acceleration().
subroutine, public convection_mod::compute_ugradu_z (integer(c_int), dimension(3), intent(in) lo, integer(c_int), dimension(3), intent(in) hi, real(ar), dimension(ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(in) ug, integer(c_int), dimension(3), intent(in) ulo, integer(c_int), dimension(3), intent(in) uhi, real(ar), dimension(vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3)), intent(in) vg, integer(c_int), dimension(3), intent(in) vlo, integer(c_int), dimension(3), intent(in) vhi, real(ar), dimension(wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3)), intent(in) wg, integer(c_int), dimension(3), intent(in) wlo, integer(c_int), dimension(3), intent(in) whi, real(ar), dimension(wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3),3), intent(in) slopes, real(ar), dimension(wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3)), intent(out) ugradu_z, real(ar), dimension(3), intent(in) dx)
References avg_functions::avg().
Referenced by projection_mod::compute_fluid_acceleration().
The documentation for this module was generated from the following file:
mfix/src/projection/convection_mod.f90