MFiX-Exa: read_namelist_module Module Reference
read_namelist_module Module Reference
Public Member Functions
subroutine read_namelist (dt)
subroutine add_argument (fname, nlen)
Member Function/Subroutine Documentation
subroutine read_namelist_module::add_argument (character(kind=c_char), dimension(nlen), intent(in) fname, integer(c_int), intent(in) nlen)
subroutine read_namelist_module::read_namelist (real(c_real), intent(out) dt)
References utilities::blank_line(), deprecated_or_unknown_module::deprecated_or_unknown(), error_manager::finl_err_msg(), error_manager::flush_err_msg(), error_manager::init_err_msg(), error_manager::ivar(), utilities::line_too_big(), utilities::make_upper_case(), remove_comment_module::remove_comment(), remove_comment_module::remove_par_blanks(), utilities::replace_tab(), utilities::seek_comment(), and set_keyword().
Referenced by get_data_module::get_data().
The documentation for this module was generated from the following file:
mfix/src/read_namelist.f90