MFiX-Exa: output_manager_module Module Reference
output_manager_module Module Reference
Public Member Functions
subroutine, public output_manager (np, time, dt, xlength, ylength, zlength, nstep, particles, finished)
Member Function/Subroutine Documentation
subroutine, public output_manager_module::output_manager (integer(c_int), intent(in) np, real(c_real), intent(in) time, real(c_real), intent(in) dt, real(c_real), intent(in) xlength, real(c_real), intent(in) ylength, real(c_real), intent(in) zlength, integer(c_int), intent(in) nstep, type(particle_t), dimension(np), intent(in) particles, integer(c_int), intent(in) finished)
References check_time(), flush_list(), flush_notify_user(), and write_usr1().
The documentation for this module was generated from the following file:
mfix/src/io/output_manager.f90