MFiX-Exa: utilities Module Reference
utilities Module Reference
Public Member Functions
logical function mfix_isnan (x)
pure integer function seek_comment (LINE, MAXCOL)
pure integer function seek_end (LINE, MAXCOL)
pure integer function line_too_big (LINE, LINE_LEN, MAXCOL)
pure logical function blank_line (line)
subroutine make_upper_case (LINE_STRING, MAXCOL)
subroutine replace_tab (LINE_STRING, MAXCOL)
Member Function/Subroutine Documentation
pure logical function utilities::blank_line (character, dimension(*), intent(in) line)
Referenced by init_namelist_module::init_namelist(), and read_namelist_module::read_namelist().
pure integer function utilities::line_too_big (character(len=*), intent(in) LINE, integer, intent(in) LINE_LEN, integer, intent(in) MAXCOL)
Referenced by init_namelist_module::init_namelist(), and read_namelist_module::read_namelist().
subroutine utilities::make_upper_case (character(len=*), intent(inout) LINE_STRING, integer, intent(in) MAXCOL)
Referenced by init_namelist_module::init_namelist(), read_namelist_module::read_namelist(), and set_keyword().
logical function utilities::mfix_isnan (real(c_real) x)
subroutine utilities::replace_tab (character(len=*), intent(inout) LINE_STRING, integer, intent(in) MAXCOL)
Referenced by init_namelist_module::init_namelist(), read_namelist_module::read_namelist(), and set_keyword().
pure integer function utilities::seek_comment (character(len=*), intent(in) LINE, integer, intent(in) MAXCOL)
Referenced by init_namelist_module::init_namelist(), and read_namelist_module::read_namelist().
pure integer function utilities::seek_end (character, dimension(*), intent(in) LINE, integer, intent(in) MAXCOL)
Referenced by parse_line_module::parse_arith().
The documentation for this module was generated from the following file:
mfix/src/utilities_mod.f90