MFiX-Exa: ParticlesGenerator Class Reference
ParticlesGenerator Class Reference
#include <mfix_particle_generator.H>
Public Types
using ParticleType = MFIXParticleContainer::ParticleType
using ParticleTileType = MFIXParticleContainer::ParticleTileType
Public Member Functions
ParticlesGenerator ()
~ParticlesGenerator ()
void generate (int &pc, const amrex::IntVect &lo, const amrex::IntVect &hi, const amrex::Real dx, const amrex::Real dy, const amrex::Real dz, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &plo)
void generate_prop (const int nrp, ParticleTileType &particles)
void write (const int nrp, const ParticleTileType &particles, const int nstep=0) const
void hex_close_pack (const int icv, const int type, const amrex::IntVect &lo, const amrex::IntVect &hi, int &np, int &pc, const amrex::Real dx, const amrex::Real dy, const amrex::Real dz, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &plo)
void one_per_fill (const int icv, const int type, const amrex::IntVect &lo, const amrex::IntVect &hi, int &np, int &pc, const amrex::Real dx, const amrex::Real dy, const amrex::Real dz, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &plo)
void eight_per_fill (const int icv, const int type, const amrex::IntVect &lo, const amrex::IntVect &hi, int &np, int &pc, const amrex::Real dx, const amrex::Real dy, const amrex::Real dz, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &plo)
void random_fill_dem (const int icv, const int type, const amrex::IntVect &lo, const amrex::IntVect &hi, int &np, int &pc, const amrex::Real dx, const amrex::Real dy, const amrex::Real dz, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &plo, const bool fix_seed)
void random_fill_pic (const int icv, const int type, const amrex::IntVect &lo, const amrex::IntVect &hi, int &np, int &pc, const amrex::Real dx, const amrex::Real dy, const amrex::Real dz, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &plo, const bool fix_seed)
void nor_rno (amrex::Gpu::DeviceVector< amrex::Real > &dp, const amrex::Real mean, const amrex::Real sigma, const amrex::Real dp_min, const amrex::Real dp_max)
void uni_rno (amrex::Gpu::DeviceVector< amrex::Real > &dp, const amrex::Real dp_min, const amrex::Real dp_max)
void grow_pdata (const int gsize)
Member Typedef Documentation
using ParticlesGenerator::ParticleTileType = MFIXParticleContainer::ParticleTileType
using ParticlesGenerator::ParticleType = MFIXParticleContainer::ParticleType
Constructor & Destructor Documentation
ParticlesGenerator::ParticlesGenerator () explicit
ParticlesGenerator::~ParticlesGenerator ()
Member Function Documentation
void ParticlesGenerator::eight_per_fill (const int icv, const int type, const amrex::IntVect & lo, const amrex::IntVect & hi, int & np, int & pc, const amrex::Real dx, const amrex::Real dy, const amrex::Real dz, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & plo)
References grow_pdata().
Referenced by generate().
void ParticlesGenerator::generate (int & pc, const amrex::IntVect & lo, const amrex::IntVect & hi, const amrex::Real dx, const amrex::Real dy, const amrex::Real dz, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & plo)
References eight_per_fill(), hex_close_pack(), nor_rno(), one_per_fill(), random_fill_dem(), random_fill_pic(), and uni_rno().
Referenced by MFIXParticleContainer::InitParticlesAuto().
void ParticlesGenerator::generate_prop (const int nrp, ParticleTileType & particles)
References realData::density, realData::dragcoeff, realData::dragx, realData::dragy, realData::dragz, realData::mass, realData::omegax, realData::omegay, realData::omegaz, realData::oneOverI, intData::phase, realData::radius, intData::state, realData::statwt, realData::velx, realData::vely, realData::velz, and realData::volume.
Referenced by MFIXParticleContainer::InitParticlesAuto().
void ParticlesGenerator::grow_pdata (const int gsize)
Referenced by eight_per_fill(), hex_close_pack(), one_per_fill(), random_fill_dem(), and random_fill_pic().
void ParticlesGenerator::hex_close_pack (const int icv, const int type, const amrex::IntVect & lo, const amrex::IntVect & hi, int & np, int & pc, const amrex::Real dx, const amrex::Real dy, const amrex::Real dz, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & plo)
References grow_pdata().
Referenced by generate().
void ParticlesGenerator::nor_rno (amrex::Gpu::DeviceVector< amrex::Real > & dp, const amrex::Real mean, const amrex::Real sigma, const amrex::Real dp_min, const amrex::Real dp_max)
Referenced by generate().
void ParticlesGenerator::one_per_fill (const int icv, const int type, const amrex::IntVect & lo, const amrex::IntVect & hi, int & np, int & pc, const amrex::Real dx, const amrex::Real dy, const amrex::Real dz, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & plo)
References grow_pdata().
Referenced by generate().
void ParticlesGenerator::random_fill_dem (const int icv, const int type, const amrex::IntVect & lo, const amrex::IntVect & hi, int & np, int & pc, const amrex::Real dx, const amrex::Real dy, const amrex::Real dz, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & plo, const bool fix_seed)
References grow_pdata().
Referenced by generate().
void ParticlesGenerator::random_fill_pic (const int icv, const int type, const amrex::IntVect & lo, const amrex::IntVect & hi, int & np, int & pc, const amrex::Real dx, const amrex::Real dy, const amrex::Real dz, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & plo, const bool fix_seed)
References grow_pdata().
Referenced by generate().
void ParticlesGenerator::uni_rno (amrex::Gpu::DeviceVector< amrex::Real > & dp, const amrex::Real dp_min, const amrex::Real dp_max)
Referenced by generate().
void ParticlesGenerator::write (const int nrp, const ParticleTileType & particles, const int nstep = 0) const
References realData::density, and realData::radius.
The documentation for this class was generated from the following files:
mfix/src/des/mfix_particle_generator.H
mfix/src/des/mfix_particle_generator.cpp