MFiX-Exa: wall_collisions Module Reference
wall_collisions Module Reference
Public Member Functions
subroutine calc_wall_collisions (particles, np, nrp, tow, fc, dtsolid, flag, fglo, fghi, normal, nlo, nhi, bcent, blo, bhi, dx)
subroutine calc_wall_collisions_ls (particles, np, nrp, tow, fc, dtsolid, valid, vlo, vhi, phi, phlo, phhi, dx, n_refine)
subroutine cfrelvel_wall (ll, vrn, vrt, norm, dist, particles)
Member Function/Subroutine Documentation
subroutine wall_collisions::calc_wall_collisions (type(particle_t), dimension(np), intent(in), target particles, integer, intent(in) np, integer, intent(in) nrp, real(rt), dimension(np,3), intent(inout) tow, real(rt), dimension(np,3), intent(inout) fc, real(rt), intent(in) dtsolid, integer, dimension(fglo(1):fghi(1),fglo(2):fghi(2),fglo(3):fghi(3)), intent(in) flag, integer, dimension(3), intent(in) fglo, integer, dimension(3), intent(in) fghi, real(rt), dimension(nlo(1):nhi(1),nlo(2):nhi(2),nlo(3):nhi(3),3), intent(in) normal, integer, dimension(3), intent(in) nlo, integer, dimension(3), intent(in) nhi, real(rt), dimension(blo(1):bhi(1),blo(2):bhi(2),blo(3):bhi(3),3), intent(in) bcent, integer, dimension(3), intent(in) blo, integer, dimension(3), intent(in) bhi, real(rt), dimension(3), intent(in) dx)
References cfrelvel_wall(), and discretelement::des_crossprdct().
subroutine wall_collisions::calc_wall_collisions_ls (type(particle_t), dimension(np), intent(in), target particles, integer, intent(in) np, integer, intent(in) nrp, real(rt), dimension(np,3), intent(inout) tow, real(rt), dimension(np,3), intent(inout) fc, real(rt), intent(in) dtsolid, integer, dimension(vlo(1): vhi(1), vlo(2): vhi(2), vlo(3): vhi(3)), intent(in) valid, integer, dimension(3), intent(in) vlo, integer, dimension(3), intent(in) vhi, real(rt), dimension(phlo(1):phhi(1), phlo(2):phhi(2), phlo(3):phhi(3)), intent(in) phi, integer, dimension(3), intent(in) phlo, integer, dimension(3), intent(in) phhi, real(rt), dimension(3), intent(in) dx, integer, intent(in) n_refine)
References cfrelvel_wall(), and discretelement::des_crossprdct().
subroutine wall_collisions::cfrelvel_wall (integer, intent(in) ll, real(rt), intent(out) vrn, real(rt), dimension(3), intent(out) vrt, real(rt), dimension(3), intent(in) norm, real(rt), intent(in) dist, type(particle_t), dimension(:), intent(in) particles)
References discretelement::des_crossprdct().
Referenced by calc_wall_collisions(), and calc_wall_collisions_ls().
The documentation for this module was generated from the following file:
mfix/src/des/calc_wall_collisions.f90