MFiX-Exa: param Module Reference
param Module Reference
Data Types
interface is_defined
interface is_undefined
Public Member Functions
pure logical function is_defined_db (x)
pure logical function is_defined_i (x)
pure logical function is_undefined_db (x)
pure logical function is_undefined_i (x)
pure logical function equal (x, y)
Public Attributes
integer, parameter dim_ic = 500
integer, parameter dim_bc = 500
integer, parameter dim_ps = 5000
integer, parameter dim_m = 10
integer, parameter dim_n_g = 100
integer, parameter dim_n_s = 100
integer, parameter dim_usr = 5
integer, parameter dim_eqs = 4
real(c_real), parameter undefined = 9.87654321d31
integer, parameter undefined_i = 987654321
character, parameter undefined_c = ' '
real(c_real), parameter large_number = 1.0d32
real(c_real), parameter small_number = 1.0d-15
real(c_real), parameter zero = 0.0d0
real(c_real), parameter half = 0.5d0
real(c_real), parameter one = 1.0d0
Member Function/Subroutine Documentation
pure logical function param::equal (real(c_real), intent(in) x, real(c_real), intent(in) y)
Referenced by calc_cell_module::calc_cell_bc_flow(), calc_cell_module::calc_cell_bc_wall(), calc_cell_module::calc_cell_ic(), calc_cell_module::calc_cell_ps(), cfslide_module::cfslide(), check_bc_inflow_module::check_bc_mass_inflow(), check_bc_outflow_module::check_bc_outflow(), check_bc_range(), check_boundary_conditions_module::check_boundary_conditions(), check_initial_conditions_module::check_ic_solids_phases(), check_point_sources_module::check_ps_gas_phase(), set_bc_flow_module::flow_to_vel(), is_defined_db(), is_undefined_db(), set_bc_type_module::set_bc_type(), and ur_facs::under_relax().
pure logical function param::is_defined_db (real(c_real), intent(in) x)
References equal(), and param::is_defined::is_defined_db().
pure logical function param::is_defined_i (integer, intent(in) x)
References param::is_defined::is_defined_i().
pure logical function param::is_undefined_db (real(c_real), intent(in) x)
References equal(), and param::is_undefined::is_undefined_db().
pure logical function param::is_undefined_i (integer, intent(in) x)
References param::is_undefined::is_undefined_i().
Member Data Documentation
integer, parameter param::dim_bc = 500
integer, parameter param::dim_eqs = 4
integer, parameter param::dim_ic = 500
integer, parameter param::dim_m = 10
integer, parameter param::dim_n_g = 100
integer, parameter param::dim_n_s = 100
integer, parameter param::dim_ps = 5000
integer, parameter param::dim_usr = 5
real(c_real), parameter param::half = 0.5d0
real(c_real), parameter param::large_number = 1.0d32
real(c_real), parameter param::one = 1.0d0
real(c_real), parameter param::small_number = 1.0d-15
real(c_real), parameter param::undefined = 9.87654321d31
character, parameter param::undefined_c = ' '
integer, parameter param::undefined_i = 987654321
real(c_real), parameter param::zero = 0.0d0
The documentation for this module was generated from the following file:
mfix/src/param_mod.f90