MFiX-Exa: solve_pp_module Module Reference
solve_pp_module Module Reference
Public Member Functions
subroutine solve_pp_g (slo, shi, ulo, uhi, vlo, vhi, wlo, whi, alo, ahi, lo, hi, u_g, v_g, w_g, p_g, ep_g, rop_g, rop_go, ro_g, ropX, ropY, ropZ, d_e, d_n, d_t, A_m, b_m, b_mmax, bc_ilo_type, bc_ihi_type, bc_jlo_type, bc_jhi_type, bc_klo_type, bc_khi_type, dt, dx, dy, dz, domlo, domhi, ng, num_p, denom_p)
subroutine point_source_pp_g (lo, hi, alo, ahi, b_m, B_mmax, dx, dy, dz)
Member Function/Subroutine Documentation
subroutine solve_pp_module::point_source_pp_g (integer(c_int), dimension(3), intent(in) lo, integer(c_int), dimension(3), intent(in) hi, integer(c_int), dimension(3), intent(in) alo, integer(c_int), dimension(3), intent(in) ahi, real(rt), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)), intent(inout) b_m, real(rt), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)), intent(inout) B_mmax, real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz)
Referenced by solve_pp_g().
subroutine solve_pp_module::solve_pp_g (integer(c_int), dimension(3), intent(in) slo, integer(c_int), dimension(3), intent(in) shi, integer(c_int), dimension(3), intent(in) ulo, integer(c_int), dimension(3), intent(in) uhi, integer(c_int), dimension(3), intent(in) vlo, integer(c_int), dimension(3), intent(in) vhi, integer(c_int), dimension(3), intent(in) wlo, integer(c_int), dimension(3), intent(in) whi, integer(c_int), dimension(3), intent(in) alo, integer(c_int), dimension(3), intent(in) ahi, integer(c_int), dimension(3), intent(in) lo, integer(c_int), dimension(3), intent(in) hi, real(rt), dimension (ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(in) u_g, real(rt), dimension (vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3)), intent(in) v_g, real(rt), dimension (wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3)), intent(in) w_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) p_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ep_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) rop_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) rop_go, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ro_g, real(rt), dimension (ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(in) ropX, real(rt), dimension (vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3)), intent(in) ropY, real(rt), dimension (wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3)), intent(in) ropZ, real(rt), dimension (ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(in) d_e, real(rt), dimension (vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3)), intent(in) d_n, real(rt), dimension (wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3)), intent(in) d_t, real(rt), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3),-3:3), intent(out) A_m, real(rt), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)), intent(out) b_m, real(rt), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)), intent(out) b_mmax, integer(c_int), dimension(domlo(2)-ng:domhi(2)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_ilo_type, integer(c_int), dimension(domlo(2)-ng:domhi(2)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_ihi_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_jlo_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_jhi_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(2)-ng:domhi(2)+ng,2), intent(in) bc_klo_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(2)-ng:domhi(2)+ng,2), intent(in) bc_khi_type, real(rt), intent(in) dt, real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz, integer(c_int), dimension(3), intent(in) domlo, integer(c_int), dimension(3), intent(in) domhi, integer(c_int), intent(in) ng, real(rt), intent(out) num_p, real(rt), intent(out) denom_p)
References residual::calc_resid_pp(), conv_pp_g_module::conv_pp_g(), point_source_pp_g(), source_pp_module::source_pp_g(), and source_pp_module::source_pp_g_bc().
The documentation for this module was generated from the following file:
mfix/src/simple/solve_pp_g.f90