MFiX-Exa: solve_vel_star_module Module Reference
solve_vel_star_module Module Reference
Public Member Functions
subroutine, public solve_u_g_star (slo, shi, ulo, uhi, vlo, vhi, wlo, whi, alo, ahi, dlo, dhi, lo, hi, u_g, v_g, w_g, u_go, p_g, p0_g, ro_g, rop_g, rop_go, ep_g, tau_u_g, d_e, fluxX, fluxY, fluxZ, mu_g, f_gds_u, drag_u, A_m, b_m, mask, bc_ilo_type, bc_ihi_type, bc_jlo_type, bc_jhi_type, bc_klo_type, bc_khi_type, domlo, domhi, ng, dt, dx, dy, dz, num_u, denom_u)
subroutine, public solve_v_g_star (slo, shi, ulo, uhi, vlo, vhi, wlo, whi, alo, ahi, dlo, dhi, lo, hi, u_g, v_g, w_g, v_go, p_g, p0_g, ro_g, rop_g, rop_go, ep_g, tau_v_g, d_n, fluxX, fluxY, fluxZ, mu_g, f_gds_v, drag_v, A_m, b_m, mask, bc_ilo_type, bc_ihi_type, bc_jlo_type, bc_jhi_type, bc_klo_type, bc_khi_type, domlo, domhi, ng, dt, dx, dy, dz, num_v, denom_v)
subroutine, public solve_w_g_star (slo, shi, ulo, uhi, vlo, vhi, wlo, whi, alo, ahi, dlo, dhi, lo, hi, u_g, v_g, w_g, w_go, p_g, p0_g, ro_g, rop_g, rop_go, ep_g, tau_w_g, d_t, fluxX, fluxY, fluxZ, mu_g, f_gds_w, drag_w, A_m, b_m, mask, bc_ilo_type, bc_ihi_type, bc_jlo_type, bc_jhi_type, bc_klo_type, bc_khi_type, domlo, domhi, ng, dt, dx, dy, dz, num_w, denom_w)
Member Function/Subroutine Documentation
subroutine, public solve_vel_star_module::solve_u_g_star (integer(c_int), dimension(3), intent(in) slo, integer(c_int), dimension(3), intent(in) shi, integer(c_int), dimension(3), intent(in) ulo, integer(c_int), dimension(3), intent(in) uhi, integer(c_int), dimension(3), intent(in) vlo, integer(c_int), dimension(3), intent(in) vhi, integer(c_int), dimension(3), intent(in) wlo, integer(c_int), dimension(3), intent(in) whi, integer(c_int), dimension(3), intent(in) alo, integer(c_int), dimension(3), intent(in) ahi, integer(c_int), dimension(3), intent(in) dlo, integer(c_int), dimension(3), intent(in) dhi, integer(c_int), dimension(3), intent(in) lo, integer(c_int), dimension(3), intent(in) hi, real(rt), dimension (ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(in) u_g, real(rt), dimension (vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3)), intent(in) v_g, real(rt), dimension (wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3)), intent(in) w_g, real(rt), dimension (ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(in) u_go, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) p_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) p0_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ro_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) rop_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) rop_go, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ep_g, real(rt), dimension(ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(in) tau_u_g, real(rt), dimension(ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(out) d_e, real(rt), dimension (ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(in) fluxX, real(rt), dimension (vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3)), intent(in) fluxY, real(rt), dimension (wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3)), intent(in) fluxZ, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) mu_g, real(rt), dimension(dlo(1):dhi(1),dlo(2):dhi(2),dlo(3):dhi(3)), intent(in) f_gds_u, real(rt), dimension (dlo(1):dhi(1),dlo(2):dhi(2),dlo(3):dhi(3)), intent(in) drag_u, real(rt), dimension(alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3),-3:3), intent(out) A_m, real(rt), dimension(alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)), intent(out) b_m, real(rt), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)), intent(in) mask, integer(c_int), dimension(domlo(2)-ng:domhi(2)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_ilo_type, integer(c_int), dimension(domlo(2)-ng:domhi(2)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_ihi_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_jlo_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_jhi_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(2)-ng:domhi(2)+ng,2), intent(in) bc_klo_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(2)-ng:domhi(2)+ng,2), intent(in) bc_khi_type, integer(c_int), dimension(3), intent(in) domlo, integer(c_int), dimension(3), intent(in) domhi, integer(c_int), intent(in) ng, real(rt), intent(in) dt, real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz, real(rt), intent(out) num_u, real(rt), intent(out) denom_u)
References adjust_a::adjust_a_u(), calc_d_mod::calc_d_e(), residual::calc_resid_vel(), u_g_conv_dif::conv_dif_u_g(), source_u_g_module::point_source_u_g(), source_u_g_module::source_u_g(), source_u_g_module::source_u_g_bc(), and ur_facs::under_relax().
subroutine, public solve_vel_star_module::solve_v_g_star (integer(c_int), dimension(3), intent(in) slo, integer(c_int), dimension(3), intent(in) shi, integer(c_int), dimension(3), intent(in) ulo, integer(c_int), dimension(3), intent(in) uhi, integer(c_int), dimension(3), intent(in) vlo, integer(c_int), dimension(3), intent(in) vhi, integer(c_int), dimension(3), intent(in) wlo, integer(c_int), dimension(3), intent(in) whi, integer(c_int), dimension(3), intent(in) alo, integer(c_int), dimension(3), intent(in) ahi, integer(c_int), dimension(3), intent(in) dlo, integer(c_int), dimension(3), intent(in) dhi, integer(c_int), dimension(3), intent(in) lo, integer(c_int), dimension(3), intent(in) hi, real(rt), dimension (ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(in) u_g, real(rt), dimension (vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3)), intent(in) v_g, real(rt), dimension (wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3)), intent(in) w_g, real(rt), dimension (vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3)), intent(in) v_go, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) p_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) p0_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ro_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) rop_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) rop_go, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ep_g, real(rt), dimension(vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3)), intent(in) tau_v_g, real(rt), dimension (vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3)), intent(out) d_n, real(rt), dimension (ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(in) fluxX, real(rt), dimension (vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3)), intent(in) fluxY, real(rt), dimension (wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3)), intent(in) fluxZ, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) mu_g, real(rt), dimension(dlo(1):dhi(1),dlo(2):dhi(2),dlo(3):dhi(3)), intent(in) f_gds_v, real(rt), dimension (dlo(1):dhi(1),dlo(2):dhi(2),dlo(3):dhi(3)), intent(in) drag_v, real(rt), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3),-3:3), intent(out) A_m, real(rt), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)), intent(out) b_m, real(rt), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)), intent(in) mask, integer(c_int), dimension(domlo(2)-ng:domhi(2)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_ilo_type, integer(c_int), dimension(domlo(2)-ng:domhi(2)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_ihi_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_jlo_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_jhi_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(2)-ng:domhi(2)+ng,2), intent(in) bc_klo_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(2)-ng:domhi(2)+ng,2), intent(in) bc_khi_type, integer(c_int), dimension(3), intent(in) domlo, integer(c_int), dimension(3), intent(in) domhi, integer(c_int), intent(in) ng, real(rt), intent(in) dt, real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz, real(rt), intent(out) num_v, real(rt), intent(out) denom_v)
References adjust_a::adjust_a_v(), calc_d_mod::calc_d_n(), residual::calc_resid_vel(), v_g_conv_dif::conv_dif_v_g(), source_v_g_module::point_source_v_g(), source_v_g_module::source_v_g(), source_v_g_module::source_v_g_bc(), and ur_facs::under_relax().
subroutine, public solve_vel_star_module::solve_w_g_star (integer(c_int), dimension(3), intent(in) slo, integer(c_int), dimension(3), intent(in) shi, integer(c_int), dimension(3), intent(in) ulo, integer(c_int), dimension(3), intent(in) uhi, integer(c_int), dimension(3), intent(in) vlo, integer(c_int), dimension(3), intent(in) vhi, integer(c_int), dimension(3), intent(in) wlo, integer(c_int), dimension(3), intent(in) whi, integer(c_int), dimension(3), intent(in) alo, integer(c_int), dimension(3), intent(in) ahi, integer(c_int), dimension(3), intent(in) dlo, integer(c_int), dimension(3), intent(in) dhi, integer(c_int), dimension(3), intent(in) lo, integer(c_int), dimension(3), intent(in) hi, real(rt), dimension (ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(in) u_g, real(rt), dimension (vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3)), intent(in) v_g, real(rt), dimension (wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3)), intent(in) w_g, real(rt), dimension (wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3)), intent(in) w_go, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) p_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) p0_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ro_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) rop_g, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) rop_go, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ep_g, real(rt), dimension(wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3)), intent(in) tau_w_g, real(rt), dimension(wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3)), intent(out) d_t, real(rt), dimension (ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(in) fluxX, real(rt), dimension (vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3)), intent(in) fluxY, real(rt), dimension (wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3)), intent(in) fluxZ, real(rt), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) mu_g, real(rt), dimension(dlo(1):dhi(1),dlo(2):dhi(2),dlo(3):dhi(3)), intent(in) f_gds_w, real(rt), dimension (dlo(1):dhi(1),dlo(2):dhi(2),dlo(3):dhi(3)), intent(in) drag_w, real(rt), dimension(alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3),-3:3), intent(out) A_m, real(rt), dimension(alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)), intent(out) b_m, real(rt), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)), intent(in) mask, integer(c_int), dimension(domlo(2)-ng:domhi(2)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_ilo_type, integer(c_int), dimension(domlo(2)-ng:domhi(2)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_ihi_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_jlo_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(3)-ng:domhi(3)+ng,2), intent(in) bc_jhi_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(2)-ng:domhi(2)+ng,2), intent(in) bc_klo_type, integer(c_int), dimension(domlo(1)-ng:domhi(1)+ng,domlo(2)-ng:domhi(2)+ng,2), intent(in) bc_khi_type, integer(c_int), dimension(3), intent(in) domlo, integer(c_int), dimension(3), intent(in) domhi, integer(c_int), intent(in) ng, real(rt), intent(in) dt, real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz, real(rt), intent(out) num_w, real(rt), intent(out) denom_w)
References adjust_a::adjust_a_w(), calc_d_mod::calc_d_t(), residual::calc_resid_vel(), w_g_conv_dif::conv_dif_w_g(), source_w_g_module::point_source_w_g(), source_w_g_module::source_w_g(), source_w_g_module::source_w_g_bc(), and ur_facs::under_relax().
The documentation for this module was generated from the following file:
mfix/src/simple/solve_vel_star.f90