MFiX-Exa: amrex_to_mfix_module Module Reference
amrex_to_mfix_module Module Reference
Public Member Functions
subroutine mfix_get_data (fluid, dem, steady_state, dt, dt_minC, dt_maxC, tstopC, max_nitC, normg, set_normg, call_udf)
subroutine mfix_usr0 ()
subroutine mfix_usr1 ()
subroutine mfix_usr2 ()
subroutine mfix_finl_err_msg ()
subroutine mfix_usr3 (u_g, ulo, uhi, v_g, vlo, vhi, w_g, wlo, whi, p_g, slo, shi, dx, dy, dz)
subroutine get_solver_params (eq_id, sweep_type, pc_type, max_it, tol)
Member Function/Subroutine Documentation
subroutine amrex_to_mfix_module::get_solver_params (integer(c_int), intent(in) eq_id, integer(c_int), intent(out) sweep_type, integer(c_int), intent(out) pc_type, integer(c_int), intent(out) max_it, real(c_real), intent(out) tol)
subroutine amrex_to_mfix_module::mfix_finl_err_msg ()
References error_manager::finl_err_msg().
subroutine amrex_to_mfix_module::mfix_get_data (integer(c_int), intent(out) fluid, integer(c_int), intent(out) dem, integer(c_int), intent(out) steady_state, real(c_real), intent(out) dt, real(c_real), intent(out) dt_minC, real(c_real), intent(out) dt_maxC, real(c_real), intent(out) tstopC, integer(c_int), intent(out) max_nitC, real(c_real), intent(out) normg, integer(c_int), intent(out) set_normg, integer(c_int), intent(out) call_udf)
References get_data_module::get_data().
subroutine amrex_to_mfix_module::mfix_usr0 ()
References usr0().
subroutine amrex_to_mfix_module::mfix_usr1 ()
References usr1().
subroutine amrex_to_mfix_module::mfix_usr2 ()
References usr2().
subroutine amrex_to_mfix_module::mfix_usr3 (real(c_real), dimension (ulo(1):uhi(1),ulo(2):uhi(2),ulo(3):uhi(3)), intent(inout) u_g, integer(c_int), dimension(3), intent(in) ulo, integer(c_int), dimension(3), intent(in) uhi, real(c_real), dimension (vlo(1):vhi(1),vlo(2):vhi(2),vlo(3):vhi(3)), intent(inout) v_g, integer(c_int), dimension(3), intent(in) vlo, integer(c_int), dimension(3), intent(in) vhi, real(c_real), dimension (wlo(1):whi(1),wlo(2):whi(2),wlo(3):whi(3)), intent(inout) w_g, integer(c_int), dimension(3), intent(in) wlo, integer(c_int), dimension(3), intent(in) whi, real(c_real), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(inout) p_g, integer(c_int), dimension(3), intent(in) slo, integer(c_int), dimension(3), intent(in) shi, real(c_real), intent(in) dx, real(c_real), intent(in) dy, real(c_real), intent(in) dz)
References usr3().
The documentation for this module was generated from the following file:
mfix/src/amrex_to_mfix.F90