MFiX-Exa: drag Module Reference
drag Module Reference
Public Member Functions
real(c_real) function c_dsxre_dv (RE)
real(c_real) function c_ds_sn (RE)
real(c_real) function c_dsxre_tl (RE)
subroutine drag_syam_obrien (lDgA, EPg, Mug, ROg, VREL, DPM)
subroutine drag_gidaspow (lDgA, EPg, Mug, ROg, ROPg, VREL, DPM)
subroutine drag_gidaspow_blend (lDgA, EPg, Mug, ROg, ROPg, VREL, DPM)
subroutine drag_wen_yu (lDgA, EPg, Mug, ROPg, VREL, DPM)
subroutine drag_koch_hill (lDgA, EPg, Mug, ROPg, VREL, DPM, DPA, PHIS)
subroutine drag_bvk (lDgA, EPg, Mug, ROPg, VREL, DPM, DPA, PHIS)
Public Attributes
integer, parameter invalid_drag =-1
integer, parameter syam_obrien =0
integer, parameter gidaspow =1
integer, parameter gidaspow_pcf =2
integer, parameter gidaspow_blend =3
integer, parameter gidaspow_blend_pcf =4
integer, parameter wen_yu =5
integer, parameter wen_yu_pcf =6
integer, parameter koch_hill =7
integer, parameter koch_hill_pcf =8
integer, parameter bvk =9
integer, parameter user_drag =11
character(64) drag_type
integer drag_type_enum = invalid_drag
real(c_real) drag_c1
real(c_real) drag_d1
Member Function/Subroutine Documentation
real(c_real) function drag::c_ds_sn (real(c_real), intent(in) RE)
Referenced by drag_gidaspow().
real(c_real) function drag::c_dsxre_dv (real(c_real), intent(in) RE)
Referenced by drag_syam_obrien().
real(c_real) function drag::c_dsxre_tl (real(c_real), intent(in) RE)
subroutine drag::drag_bvk (real(c_real), intent(out) lDgA, real(c_real), intent(in) EPg, real(c_real), intent(in) Mug, real(c_real), intent(in) ROPg, real(c_real), intent(in) VREL, real(c_real), intent(in) DPM, real(c_real), intent(in) DPA, real(c_real), intent(in) PHIS)
Referenced by des_drag_gp_module::des_drag_gp().
subroutine drag::drag_gidaspow (real(c_real), intent(out) lDgA, real(c_real), intent(in) EPg, real(c_real), intent(in) Mug, real(c_real), intent(in) ROg, real(c_real), intent(in) ROPg, real(c_real), intent(in) VREL, real(c_real), intent(in) DPM)
References c_ds_sn().
Referenced by des_drag_gp_module::des_drag_gp().
subroutine drag::drag_gidaspow_blend (real(c_real), intent(out) lDgA, real(c_real), intent(in) EPg, real(c_real), intent(in) Mug, real(c_real), intent(in) ROg, real(c_real), intent(in) ROPg, real(c_real), intent(in) VREL, real(c_real), intent(in) DPM)
Referenced by des_drag_gp_module::des_drag_gp().
subroutine drag::drag_koch_hill (real(c_real), intent(out) lDgA, real(c_real), intent(in) EPg, real(c_real), intent(in) Mug, real(c_real), intent(in) ROPg, real(c_real), intent(in) VREL, real(c_real), intent(in) DPM, real(c_real), intent(in) DPA, real(c_real), intent(in) PHIS)
Referenced by des_drag_gp_module::des_drag_gp().
subroutine drag::drag_syam_obrien (real(c_real), intent(out) lDgA, real(c_real), intent(in) EPg, real(c_real), intent(in) Mug, real(c_real), intent(in) ROg, real(c_real), intent(in) VREL, real(c_real), intent(in) DPM)
References c_dsxre_dv().
Referenced by des_drag_gp_module::des_drag_gp().
subroutine drag::drag_wen_yu (real(c_real), intent(out) lDgA, real(c_real), intent(in) EPg, real(c_real), intent(in) Mug, real(c_real), intent(in) ROPg, real(c_real), intent(in) VREL, real(c_real), intent(in) DPM)
Referenced by des_drag_gp_module::des_drag_gp().
Member Data Documentation
integer, parameter drag::bvk =9
real(c_real) drag::drag_c1
real(c_real) drag::drag_d1
character(64) drag::drag_type
integer drag::drag_type_enum = invalid_drag
integer, parameter drag::gidaspow =1
integer, parameter drag::gidaspow_blend =3
integer, parameter drag::gidaspow_blend_pcf =4
integer, parameter drag::gidaspow_pcf =2
integer, parameter drag::invalid_drag =-1
integer, parameter drag::koch_hill =7
integer, parameter drag::koch_hill_pcf =8
integer, parameter drag::syam_obrien =0
integer, parameter drag::user_drag =11
integer, parameter drag::wen_yu =5
integer, parameter drag::wen_yu_pcf =6
The documentation for this module was generated from the following file:
mfix/src/drag_mod.f90