MFiX-Exa: MFIXParticleContainer Class Reference
MFIXParticleContainer Class Reference final
#include <mfix_pc.H>
Public Types
using MFIXParIter = amrex::ParIter< realData::count, intData::count, 0, 0 >
Public Member Functions
int NumberOfParticles (MFIXParIter &pti)
MFIXParticleContainer (amrex::AmrCore *amr_core)
virtual ~MFIXParticleContainer ()
void InitData ()
void InitParticlesAscii (const std::string &file)
void InitParticlesAuto ()
void InitParticlesEnthalpy ()
void InitParticlesSpecies ()
void RemoveOutOfRange (int lev, const amrex::EBFArrayBoxFactory *ebfactory, const amrex::MultiFab *ls_phi, int ls_refinement)
void Replicate (amrex::IntVect &Nrep, amrex::Geometry &geom, amrex::DistributionMapping &dmap, amrex::BoxArray &ba)
void printParticles ()
void AllocData ()
void PrintParticleCounts ()
void EvolveParticles (int lev, int nstep, amrex::Real dt, amrex::Real time, amrex::RealVect &gravity, amrex::EBFArrayBoxFactory *ebfactory, const amrex::MultiFab *ls_phi, const int ls_refinement, amrex::MultiFab *cost, std::string &knapsack_weight_type, int &nsubsteps, const int advect_enthalpy)
void MFIX_PC_InitCollisionParams ()
void UpdateMaxVelocity ()
void UpdateMaxForces (std::map< PairIndex, amrex::Gpu::ManagedDeviceVector< amrex::Real >> pfor, std::map< PairIndex, amrex::Gpu::ManagedDeviceVector< amrex::Real >> wfor)
amrex::RealVect GetMaxVelocity ()
amrex::Vector< amrex::RealVect > GetMaxForces ()
void WriteAsciiFileForInit (const std::string &filename)
void output (int estatus, int finish, int nstep, amrex::Real dt, amrex::Real time)
void writeAllAtLevel (int lev=0)
void SolidsVolumeDeposition (int lev, amrex::MultiFab &mf, const amrex::MultiFab *volfrac, const amrex::FabArray< amrex::EBCellFlagFab > *flags)
template<typename FB >
void SolidsVolumeDeposition (FB WeightFunc, int lev, amrex::MultiFab &mf, const amrex::MultiFab *volfrac, const amrex::FabArray< amrex::EBCellFlagFab > *flags)
void InterphaseTxfrDeposition (int lev, amrex::MultiFab &mf_tmp_eps, amrex::MultiFab &txfr_mf, const amrex::MultiFab *volfrac, const amrex::FabArray< amrex::EBCellFlagFab > *flags)
template<typename F >
void InterphaseTxfrDeposition (F WeightFunc, int lev, amrex::MultiFab &mf_tmp_eps, amrex::MultiFab &txfr_mf, const amrex::MultiFab *volfrac, const amrex::FabArray< amrex::EBCellFlagFab > *flags)
void InterphaseChemDeposition (int lev, amrex::MultiFab &mf_tmp_eps, amrex::MultiFab &Rrates, const amrex::MultiFab *volfrac, const amrex::FabArray< amrex::EBCellFlagFab > *flags)
template<typename F >
void InterphaseChemDeposition (F WeightFunc, int lev, amrex::MultiFab &mf_tmp_eps, amrex::MultiFab &chem_txfr_mf, const amrex::MultiFab *volfrac, const amrex::FabArray< amrex::EBCellFlagFab > *flags)
void ComputeAverageVelocities (const int lev, const amrex::Real time, const std::string &basename, const amrex::Vector< amrex::Real > &avg_vel_p, const amrex::Vector< amrex::Real > &avg_region_x_w, const amrex::Vector< amrex::Real > &avg_region_x_e, const amrex::Vector< amrex::Real > &avg_region_y_s, const amrex::Vector< amrex::Real > &avg_region_y_n, const amrex::Vector< amrex::Real > &avg_region_z_b, const amrex::Vector< amrex::Real > &avg_region_z_t)
void MFIX_PC_CalcSolidsStressGrad (int lev, amrex::EBFArrayBoxFactory *ebfactory, amrex::MultiFab &ep_g_in, amrex::MultiFab &grad_tau_in, amrex::Vector< amrex::MultiFab * > &cost, std::string &knapsack_weight_type)
void MFIX_PC_SolidsVelocityDeposition (int lev, amrex::MultiFab &vel_s_mf, const amrex::FabArray< amrex::EBCellFlagFab > *flags)
void MFIX_PC_AdvanceParcels (amrex::Real dt, amrex::RealVect &gravity, amrex::Vector< amrex::MultiFab * > &avg_prop_in, amrex::Vector< amrex::MultiFab * > &cost, std::string &knapsack_weight_type, const int advect_enthalpy)
void MFIX_PC_ImposeWalls (int lev, amrex::EBFArrayBoxFactory *ebfactory, const int ls_refinement, const amrex::MultiFab *ls_phi, amrex::MultiFab *cost, std::string &knapsack_weight_type)
Member Typedef Documentation
using MFIXParticleContainer::MFIXParIter = amrex::ParIter<realData::count,intData::count,0,0>
Constructor & Destructor Documentation
MFIXParticleContainer::MFIXParticleContainer (amrex::AmrCore * amr_core)
virtual MFIXParticleContainer::~MFIXParticleContainer () inline virtual
Member Function Documentation
void MFIXParticleContainer::AllocData ()
void MFIXParticleContainer::ComputeAverageVelocities (const int lev, const amrex::Real time, const std::string & basename, const amrex::Vector< amrex::Real > & avg_vel_p, const amrex::Vector< amrex::Real > & avg_region_x_w, const amrex::Vector< amrex::Real > & avg_region_x_e, const amrex::Vector< amrex::Real > & avg_region_y_s, const amrex::Vector< amrex::Real > & avg_region_y_n, const amrex::Vector< amrex::Real > & avg_region_z_b, const amrex::Vector< amrex::Real > & avg_region_z_t)
References realData::mass, NumberOfParticles(), realData::velx, realData::vely, and realData::velz.
Referenced by GetMaxForces(), and mfix::WriteAverageRegions().
void MFIXParticleContainer::EvolveParticles (int lev, int nstep, amrex::Real dt, amrex::Real time, amrex::RealVect & gravity, amrex::EBFArrayBoxFactory * ebfactory, const amrex::MultiFab * ls_phi, const int ls_refinement, amrex::MultiFab * cost, std::string & knapsack_weight_type, int & nsubsteps, const int advect_enthalpy)
References realData::c_ps, cfrelvel(), realData::convection, speciesData::count, cross_product(), realData::density, dot_product(), realData::dragx, realData::dragy, realData::dragz, reactionsData::G_sn_pg_q, GetMaxForces(), GetMaxVelocity(), interp_level_set(), level_set_normal(), realData::mass, NumberOfParticles(), realData::omegax, realData::omegay, realData::omegaz, realData::oneOverI, intData::phase, realData::radius, realData::temperature, UpdateMaxForces(), UpdateMaxVelocity(), realData::velx, realData::vely, realData::velz, realData::volume, and speciesData::X_sn.
Vector< RealVect > MFIXParticleContainer::GetMaxForces ()
References ComputeAverageVelocities().
Referenced by EvolveParticles().
RealVect MFIXParticleContainer::GetMaxVelocity ()
Referenced by EvolveParticles().
void MFIXParticleContainer::InitData ()
void MFIXParticleContainer::InitParticlesAscii (const std::string & file)
References realData::c_ps, realData::convection, realData::density, realData::dragcoeff, realData::dragx, realData::dragy, realData::dragz, realData::mass, realData::omegax, realData::omegay, realData::omegaz, realData::oneOverI, intData::phase, realData::radius, intData::state, realData::statwt, realData::temperature, realData::velx, realData::vely, realData::velz, and realData::volume.
void MFIXParticleContainer::InitParticlesAuto ()
References ParticlesGenerator::generate(), and ParticlesGenerator::generate_prop().
void MFIXParticleContainer::InitParticlesEnthalpy ()
References realData::c_ps, intData::phase, and realData::temperature.
void MFIXParticleContainer::InitParticlesSpecies ()
void MFIXParticleContainer::InterphaseChemDeposition (int lev, amrex::MultiFab & mf_tmp_eps, amrex::MultiFab & Rrates, const amrex::MultiFab * volfrac, const amrex::FabArray< amrex::EBCellFlagFab > * flags)
Do the actual PIC deposition for CalcDragOnFluid
Referenced by mfix::mfix_calc_chem_txfr().
template<typename F > void MFIXParticleContainer::InterphaseChemDeposition (F WeightFunc, int lev, amrex::MultiFab & mf_tmp_eps, amrex::MultiFab & chem_txfr_mf, const amrex::MultiFab * volfrac, const amrex::FabArray< amrex::EBCellFlagFab > * flags)
void MFIXParticleContainer::InterphaseTxfrDeposition (int lev, amrex::MultiFab & mf_tmp_eps, amrex::MultiFab & txfr_mf, const amrex::MultiFab * volfrac, const amrex::FabArray< amrex::EBCellFlagFab > * flags)
Do the actual PIC deposition for CalcDragOnFluid
Referenced by mfix::mfix_calc_txfr_fluid().
template<typename F > void MFIXParticleContainer::InterphaseTxfrDeposition (F WeightFunc, int lev, amrex::MultiFab & mf_tmp_eps, amrex::MultiFab & txfr_mf, const amrex::MultiFab * volfrac, const amrex::FabArray< amrex::EBCellFlagFab > * flags)
void MFIXParticleContainer::MFIX_PC_AdvanceParcels (amrex::Real dt, amrex::RealVect & gravity, amrex::Vector< amrex::MultiFab * > & avg_prop_in, amrex::Vector< amrex::MultiFab * > & cost, std::string & knapsack_weight_type, const int advect_enthalpy)
void MFIXParticleContainer::MFIX_PC_CalcSolidsStressGrad (int lev, amrex::EBFArrayBoxFactory * ebfactory, amrex::MultiFab & ep_g_in, amrex::MultiFab & grad_tau_in, amrex::Vector< amrex::MultiFab * > & cost, std::string & knapsack_weight_type)
void MFIXParticleContainer::MFIX_PC_ImposeWalls (int lev, amrex::EBFArrayBoxFactory * ebfactory, const int ls_refinement, const amrex::MultiFab * ls_phi, amrex::MultiFab * cost, std::string & knapsack_weight_type)
void MFIXParticleContainer::MFIX_PC_InitCollisionParams ()
References realData::density, intData::phase, and realData::radius.
void MFIXParticleContainer::MFIX_PC_SolidsVelocityDeposition (int lev, amrex::MultiFab & vel_s_mf, const amrex::FabArray< amrex::EBCellFlagFab > * flags)
Deposit parcel velocity to the grid
int MFIXParticleContainer::NumberOfParticles (MFIXParIter & pti) inline
Referenced by ComputeAverageVelocities(), EvolveParticles(), and UpdateMaxForces().
void MFIXParticleContainer::output (int estatus, int finish, int nstep, amrex::Real dt, amrex::Real time)
void MFIXParticleContainer::PrintParticleCounts ()
void MFIXParticleContainer::printParticles ()
References realData::count, intData::phase, and intData::state.
void MFIXParticleContainer::RemoveOutOfRange (int lev, const amrex::EBFArrayBoxFactory * ebfactory, const amrex::MultiFab * ls_phi, int ls_refinement)
References realData::density, realData::radius, realData::statwt, realData::velx, realData::vely, and realData::velz.
void MFIXParticleContainer::Replicate (amrex::IntVect & Nrep, amrex::Geometry & geom, amrex::DistributionMapping & dmap, amrex::BoxArray & ba)
References realData::c_ps, realData::convection, realData::density, realData::dragcoeff, realData::dragx, realData::dragy, realData::dragz, realData::mass, realData::omegax, realData::omegay, realData::omegaz, realData::oneOverI, intData::phase, realData::radius, intData::state, realData::statwt, realData::temperature, realData::velx, realData::vely, realData::velz, and realData::volume.
Referenced by mfix::Restart().
void MFIXParticleContainer::SolidsVolumeDeposition (int lev, amrex::MultiFab & mf, const amrex::MultiFab * volfrac, const amrex::FabArray< amrex::EBCellFlagFab > * flags)
Referenced by mfix::mfix_calc_volume_fraction().
template<typename FB > void MFIXParticleContainer::SolidsVolumeDeposition (FB WeightFunc, int lev, amrex::MultiFab & mf, const amrex::MultiFab * volfrac, const amrex::FabArray< amrex::EBCellFlagFab > * flags)
Do the actual PIC deposition for CalcVolumeFraction
void MFIXParticleContainer::UpdateMaxForces (std::map< PairIndex, amrex::Gpu::ManagedDeviceVector< amrex::Real >> pfor, std::map< PairIndex, amrex::Gpu::ManagedDeviceVector< amrex::Real >> wfor)
References NumberOfParticles().
Referenced by EvolveParticles().
void MFIXParticleContainer::UpdateMaxVelocity ()
References realData::velx, realData::vely, and realData::velz.
Referenced by EvolveParticles().
void MFIXParticleContainer::writeAllAtLevel (int lev = 0)
Write out all particles at a level
void MFIXParticleContainer::WriteAsciiFileForInit (const std::string & filename)
Write out all particles in the format of the particle_input.dat files so we can initialize a run with them
References realData::density, intData::phase, realData::radius, realData::velx, realData::vely, and realData::velz.
The documentation for this class was generated from the following files:
mfix/src/des/mfix_pc.H
mfix/src/des/mfix_pc.cpp
mfix/src/des/mfix_pc_init.cpp
mfix/src/des/mfix_pc_init_collision_params.cpp
mfix/src/des/mfix_pc_remove_out_of_range.cpp
mfix/src/des/mfix_pc_replicate.cpp
mfix/src/usr/mfix_pc_usr.cpp