MFiX-Exa: eos Module Reference
eos Module Reference
Public Member Functions
real(c_real) function eosg (mw, pg, tg)
real(c_real) function droodp_g (rog, pg)
real(c_real) function sutherland (tg)
Member Function/Subroutine Documentation
real(c_real) function eos::droodp_g (real(c_real), intent(in) rog, real(c_real), intent(in) pg)
Referenced by source_pp_module::source_pp_g().
real(c_real) function eos::eosg (real(c_real), intent(in) mw, real(c_real), intent(in) pg, real(c_real), intent(in) tg)
References scales::unscale_pressure().
Referenced by calc_ro_g_module::calc_ro_g(), set_bc_flow_module::flow_to_vel(), set_bc0(), and init_fluid_module::set_p_g().
real(c_real) function eos::sutherland (real(c_real), intent(in) tg)
Referenced by calc_mu_g_module::calc_mu_g(), and set_bc0().
The documentation for this module was generated from the following file:
mfix/src/eos_mod.f90