MFiX-Exa: source_u_g_module Module Reference
source_u_g_module Module Reference
Public Member Functions
subroutine source_u_g (lo, hi, slo, shi, ulo, uhi, alo, ahi, dlo, dhi, A_m, b_m, p_g, ep_g, ro_g, rop_go, u_go, tau_u_g, f_gds_u, drag_u, dt, dx, dy, dz, domlo, domhi)
subroutine source_u_g_bc (lo, hi, slo, shi, alo, ahi, A_m, b_m, bc_ilo_type, bc_ihi_type, bc_jlo_type, bc_jhi_type, bc_klo_type, bc_khi_type, domlo, domhi, dy, dz)
subroutine point_source_u_g (lo, hi, alo, ahi, b_m, vol)
Member Function/Subroutine Documentation
subroutine source_u_g_module::point_source_u_g (integer(c_int), dimension(3), intent(in) lo, integer(c_int), dimension(3), intent(in) hi, integer(c_int), dimension(3), intent(in) alo, integer(c_int), dimension(3), intent(in) ahi, real(c_real), dimension(alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)), intent(inout) b_m, real(c_real), intent(in) vol)
Referenced by solve_vel_star_module::solve_u_g_star().
subroutine source_u_g_module::source_u_g (integer, dimension(3), intent(in) lo, integer, dimension(3), intent(in) hi, integer, dimension(3), intent(in) slo, integer, dimension(3), intent(in) shi, integer, dimension(3), intent(in) ulo, integer, dimension(3), intent(in) uhi, integer, dimension(3), intent(in) alo, integer, dimension(3), intent(in) ahi, integer, dimension(3), intent(in) dlo, integer, dimension(3), intent(in) dhi, real(c_real), dimension(alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3),-3:3), intent(inout) A_m, real(c_real), dimension(alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)), intent(inout) b_m, real(c_real), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) p_g, real(c_real), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ep_g, real(c_real), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) ro_g, real(c_real), dimension (slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) rop_go, u_go, tau_u_g, f_gds_u, drag_u, real(c_real), intent(in) dt, real(c_real), intent(in) dx, real(c_real), intent(in) dy, real(c_real), intent(in) dz, integer, dimension(3), intent(in) domlo, integer, dimension(3), intent(in) domhi)
Referenced by solve_vel_star_module::solve_u_g_star().
subroutine source_u_g_module::source_u_g_bc (integer, dimension(3), intent(in) lo, integer, dimension(3), intent(in) hi, integer, dimension(3), intent(in) slo, integer, dimension(3), intent(in) shi, integer, dimension(3), intent(in) alo, integer, dimension(3), intent(in) ahi, real(c_real), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3),-3:3), intent(inout) A_m, real(c_real), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)), intent(inout) b_m, integer(c_int), dimension (domlo(2)-2:domhi(2)+2,domlo(3)-2:domhi(3)+2,2), intent(in) bc_ilo_type, integer(c_int), dimension (domlo(2)-2:domhi(2)+2,domlo(3)-2:domhi(3)+2,2), intent(in) bc_ihi_type, integer(c_int), dimension (domlo(1)-2:domhi(1)+2,domlo(3)-2:domhi(3)+2,2), intent(in) bc_jlo_type, integer(c_int), dimension (domlo(1)-2:domhi(1)+2,domlo(3)-2:domhi(3)+2,2), intent(in) bc_jhi_type, integer(c_int), dimension (domlo(1)-2:domhi(1)+2,domlo(2)-2:domhi(2)+2,2), intent(in) bc_klo_type, integer(c_int), dimension (domlo(1)-2:domhi(1)+2,domlo(2)-2:domhi(2)+2,2), intent(in) bc_khi_type, integer, dimension(3), intent(in) domlo, integer, dimension(3), intent(in) domhi, real(c_real), intent(in) dy, real(c_real), intent(in) dz)
Referenced by solve_vel_star_module::solve_u_g_star().
The documentation for this module was generated from the following file:
mfix/src/source_u_g.f90