MFiX-Exa: ic Module Reference
ic Module Reference
Public Member Functions
logical function ic_defined (icv)
subroutine write_out_ic (unit_out, dx, dy, dz)
Public Attributes
real(c_real), dimension(dim_ic) ic_x_w
real(c_real), dimension(dim_ic) ic_x_e
real(c_real), dimension(dim_ic) ic_y_s
real(c_real), dimension(dim_ic) ic_y_n
real(c_real), dimension(dim_ic) ic_z_b
real(c_real), dimension(dim_ic) ic_z_t
real(c_real), dimension(dim_ic) ic_ep_g
real(c_real), dimension(dim_ic,
dim_m) ic_ep_s
real(c_real), dimension(dim_ic) ic_p_g
real(c_real), dimension(dim_ic) ic_u_g
real(c_real), dimension(dim_ic,
dim_m) ic_u_s
real(c_real), dimension(dim_ic) ic_v_g
real(c_real), dimension(dim_ic,
dim_m) ic_v_s
real(c_real), dimension(dim_ic) ic_w_g
real(c_real), dimension(dim_ic,
dim_m) ic_w_s
real(c_real), dimension(dim_ic) ic_t_g
real(c_real), dimension(dim_ic,
dim_m) ic_t_s
real(c_real), dimension(dim_ic,
dim_n_g) ic_x_g
real(c_real), dimension(dim_ic,
dim_m, dim_n_s) ic_x_s
Member Function/Subroutine Documentation
logical function ic::ic_defined (integer, intent(in) icv)
Referenced by check_initial_conditions_module::check_ic_common_discrete(), check_initial_conditions_module::check_ic_geometry(), check_initial_conditions_module::check_initial_conditions(), init_fluid_module::set_ic(), init_fluid_module::set_p_g(), and write_out_ic().
subroutine ic::write_out_ic (integer, intent(in) unit_out, real(c_real), intent(in) dx, real(c_real), intent(in) dy, real(c_real), intent(in) dz)
References calc_cell_module::calc_cell_ic(), and ic_defined().
Referenced by write_out0().
Member Data Documentation
real(c_real), dimension(dim_ic) ic::ic_ep_g
real(c_real), dimension(dim_ic, dim_m) ic::ic_ep_s
real(c_real), dimension(dim_ic) ic::ic_p_g
real(c_real), dimension(dim_ic) ic::ic_t_g
real(c_real), dimension(dim_ic, dim_m) ic::ic_t_s
real(c_real), dimension(dim_ic) ic::ic_u_g
real(c_real), dimension(dim_ic, dim_m) ic::ic_u_s
real(c_real), dimension(dim_ic) ic::ic_v_g
real(c_real), dimension(dim_ic, dim_m) ic::ic_v_s
real(c_real), dimension(dim_ic) ic::ic_w_g
real(c_real), dimension(dim_ic, dim_m) ic::ic_w_s
real(c_real), dimension(dim_ic) ic::ic_x_e
real(c_real), dimension(dim_ic, dim_n_g) ic::ic_x_g
real(c_real), dimension(dim_ic, dim_m, dim_n_s) ic::ic_x_s
real(c_real), dimension(dim_ic) ic::ic_x_w
real(c_real), dimension(dim_ic) ic::ic_y_n
real(c_real), dimension(dim_ic) ic::ic_y_s
real(c_real), dimension(dim_ic) ic::ic_z_b
real(c_real), dimension(dim_ic) ic::ic_z_t
The documentation for this module was generated from the following file:
mfix/src/ic_mod.f90