MFiX-Exa: des_time_march_module Module Reference
des_time_march_module Module Reference
Public Member Functions
subroutine des_init_time_loop (tstart, dt, nsubsteps, subdt)
subroutine call_usr3_des (np, particles)
subroutine call_usr2_des (np, particles)
subroutine des_time_loop_ops (nrp, rparticles, ngp, gparticles, subdt, dx, dy, dz, xlength, ylength, zlength, nstep, ncoll)
subroutine des_time_loop_ops_nl (nrp, rparticles, ngp, gparticles, size_nl, nbor_list, subdt, dx, dy, dz, xlength, ylength, zlength, nstep, ncoll)
subroutine des_euler_update (particles, grid_nbors, fc, tow, dt)
Member Function/Subroutine Documentation
subroutine des_time_march_module::call_usr2_des (integer(c_int), intent(in) np, type(particle_t), dimension(np), intent(inout) particles)
References usr2_des().
subroutine des_time_march_module::call_usr3_des (integer(c_int), intent(in) np, type(particle_t), dimension(np), intent(inout) particles)
References usr3_des().
subroutine des_time_march_module::des_euler_update (type(particle_t), dimension(:), intent(inout) particles, type(particle_t), dimension(:), intent(inout) grid_nbors, real(c_real), dimension(:,:), intent(inout) fc, real(c_real), dimension(:,:), intent(inout) tow, real(c_real), intent(in) dt)
Referenced by des_time_loop_ops(), and des_time_loop_ops_nl().
subroutine des_time_march_module::des_init_time_loop (real(c_real), intent(in) tstart, real(c_real), intent(in) dt, integer(c_int), intent(out) nsubsteps, real(c_real), intent(out) subdt)
References des_continuum_coupled().
subroutine des_time_march_module::des_time_loop_ops (integer(c_int), intent(in) nrp, type(particle_t), dimension(nrp), intent(inout) rparticles, integer(c_int), intent(in) ngp, type(particle_t), dimension(ngp), intent(inout) gparticles, real(c_real), intent(in) subdt, real(c_real), intent(in) dx, real(c_real), intent(in) dy, real(c_real), intent(in) dz, real(c_real), intent(in) xlength, real(c_real), intent(in) ylength, real(c_real), intent(in) zlength, integer(c_int), intent(in) nstep, integer(c_int), intent(inout) ncoll)
References calc_collision_wall::calc_dem_force_with_wall_stl(), calc_force_dem_module::calc_force_dem(), calc_force_dem_module::calc_force_dem_nl(), des_euler_update(), output_manager(), and usr1_des().
subroutine des_time_march_module::des_time_loop_ops_nl (integer(c_int), intent(in) nrp, type(particle_t), dimension(nrp), intent(inout) rparticles, integer(c_int), intent(in) ngp, type(particle_t), dimension(ngp), intent(inout) gparticles, integer(c_int), intent(in) size_nl, integer(c_int), dimension(size_nl), intent(in) nbor_list, real(c_real), intent(in) subdt, real(c_real), intent(in) dx, real(c_real), intent(in) dy, real(c_real), intent(in) dz, real(c_real), intent(in) xlength, real(c_real), intent(in) ylength, real(c_real), intent(in) zlength, integer(c_int), intent(in) nstep, integer(c_int), intent(inout) ncoll)
References calc_collision_wall::calc_dem_force_with_wall_stl(), calc_force_dem_module::calc_force_dem_nl(), des_euler_update(), output_manager(), and usr1_des().
The documentation for this module was generated from the following file:
mfix/src/des/des_time_march.f90