MFiX-Exa: mfix_level Class Reference
mfix_level Class Reference
#include <mfix_level.H>
Public Member Functions
mfix_level ()
~mfix_level ()
void InitParams (int solve_fluid, int solve_dem, int max_nit, int call_udf)
void Init (int lev, Real dt, Real time)
void InitLevelData (int lev, Real dt, Real time)
void PostInit (int lev, Real dt, Real time, int nstep, int restart_flag, Real stop_time, int steady_state)
void ResizeArrays ()
void WriteCheckPointFile (std::string &check_file_name, int nstep=0, Real dt=0.0, Real time=0.0) const
void WritePlotFile (std::string &plot_file_name, int nstep=0, Real dt=0.0, Real time=0.0) const
void Restart (std::string &restart_chkfile, int *nstep, Real *dt, Real *time, IntVect &Nrep)
void WriteParticleAscii (std::string &par_ascii_file_name, int nstep=0) const
void WriteUSER (int lev, Real dt, Real time) const
void Regrid (int lev, int nstep)
void Evolve (int lev, int nstep, int set_normg, int steady_state, Real &dt, Real &prev_dt, Real time, Real stop_time, Real normg)
void usr3 (int lev)
void output (int lev, int estatus, int finish, int nstep, Real dt, Real time)
void make_mg_bc (int mg_bc[])
void make_eb_geometry (int lev)
std::unique_ptr< UnionListIF
< EB2::PlaneIF > > get_walls (int lev, bool &has_walls)
std::unique_ptr< UnionListIF
< EB2::PlaneIF > > get_real_walls (int lev, bool &has_real_walls)
std::unique_ptr
< EB2::TranslationIF
< EB2::PolynomialIF > > get_poly (int lev, int max_order, std::string field_prefix)
std::unique_ptr
< EB2::IntersectionIF
< EB2::PlaneIF, EB2::PlaneIF,
EB2::PlaneIF > > make_wall (int dir, Real position, Real height, Real width)
void WriteEBSurface (int lev)
void InitIOData ()
Static Public Member Functions
static std::string get_load_balance_type ()
Public Attributes
bool levelset__restart = false
bool legacy__eb_collisions = false
int levelset__refinement = 1
int levelset__eb_refinement = 1
int levelset__pad = 2
int levelset__eb_pad = 2
Protected Member Functions
virtual void ErrorEst (int lev, amrex::TagBoxArray &tags, amrex::Real time, int) override
Tagging cells for refinement.
virtual void MakeNewLevelFromCoarse (int lev, amrex::Real time, const amrex::BoxArray &ba, const amrex::DistributionMapping &dm) override
virtual void RemakeLevel (int lev, amrex::Real time, const amrex::BoxArray &ba, const amrex::DistributionMapping &dm) override
virtual void ClearLevel (int lev) override
Delete level data. Called by AmrCore::regrid.
void mfix_calc_trd_and_tau (int lev)
void mfix_init_fluid (int lev, int is_restarting, Real dt, Real stop_time, int steady_state)
void mfix_set_bc0 (int lev)
void mfix_set_p0 (int lev)
void mfix_conv_rop (int lev)
void mfix_calc_mflux (int lev)
void mfix_solve_for_u (int lev, Real dt, Real &num_u, Real &denom_u)
void mfix_solve_for_v (int lev, Real dt, Real &num_v, Real &denom_v)
void mfix_solve_for_w (int lev, Real dt, Real &num_w, Real &denom_w)
void mfix_project_velocity (int lev)
void mfix_initial_iterations (int lev, Real dt, Real stop_time, int steady_state)
void mfix_set_projection_bcs (int lev)
void mfix_set_velocity_bcs (int lev)
void mfix_solve_linear_equation (int eq_id, int lev, MultiFab &sol, MultiFab &matrix, MultiFab &rhs)
void mfix_solve_for_pp (int lev, Real dt, Real &num_p, Real &denom_p)
void mfix_correct_0 (int lev)
int solve_bicgstab (MultiFab &sol, const MultiFab &rhs, const MultiFab &matrix, int sweep_type, int precond_type, int maxiter, Real eps_rel, int lev)
void mfix_calc_volume_fraction (int lev, Real &sum_vol)
void mfix_calc_drag_fluid (int lev)
void mfix_calc_drag_particle (int lev)
void AllocateArrays (int lev)
void RegridArrays (int lev, BoxArray &new_grids, DistributionMapping &new_dmap)
void MakeBCArrays ()
Constructor & Destructor Documentation
mfix_level::mfix_level ()
mfix_level::~mfix_level ()
Member Function Documentation
void mfix_level::AllocateArrays (int lev) protected
Referenced by InitLevelData(), and Restart().
virtual void mfix_level::ClearLevel (int lev) inline override protected virtual
Delete level data. Called by AmrCore::regrid.
virtual void mfix_level::ErrorEst (int lev, amrex::TagBoxArray & tags, amrex::Real time, int) inline override protected virtual
Tagging cells for refinement.
void mfix_level::Evolve (int lev, int nstep, int set_normg, int steady_state, Real & dt, Real & prev_dt, Real time, Real stop_time, Real normg)
References mfix_calc_drag_particle(), and mfix_calc_volume_fraction().
Referenced by main().
std::string mfix_level::get_load_balance_type () inline static
Referenced by main().
std::unique_ptr< BaseIF > mfix_level::get_poly (int lev, int max_order, std::string field_prefix)
std::unique_ptr< BaseIF > mfix_level::get_real_walls (int lev, bool & has_real_walls)
References mfix_get_real_walls().
std::unique_ptr< BaseIF > mfix_level::get_walls (int lev, bool & has_walls)
References mfix_get_walls().
void mfix_level::Init (int lev, Real dt, Real time)
References InitIOData(), levelset__eb_pad, levelset__eb_refinement, levelset__pad, levelset__refinement, mfix_set_cyclic(), set_ps(), write_out0(), and write_usr0().
Referenced by main().
void mfix_level::InitIOData ()
Referenced by Init().
void mfix_level::InitLevelData (int lev, Real dt, Real time)
References AllocateArrays(), and make_eb_geometry().
Referenced by main().
void mfix_level::InitParams (int solve_fluid, int solve_dem, int max_nit, int call_udf)
References legacy__eb_collisions, levelset__eb_pad, levelset__eb_refinement, levelset__pad, and levelset__refinement.
Referenced by main().
void mfix_level::make_eb_geometry (int lev)
Referenced by InitLevelData(), and Restart().
void mfix_level::make_mg_bc (int mg_bc[])
std::unique_ptr< BaseIF > mfix_level::make_wall (int dir, Real position, Real height, Real width)
void mfix_level::MakeBCArrays () protected
virtual void mfix_level::MakeNewLevelFromCoarse (int lev, amrex::Real time, const amrex::BoxArray & ba, const amrex::DistributionMapping & dm) inline override protected virtual
Make a new level using provided BoxArray and DistributionMapping and fill with interpolated coarse level data. Called by AmrCore::regrid.
void mfix_level::mfix_calc_drag_fluid (int lev) protected
References calc_particle_beta(), and mfix_set_velocity_bcs().
Referenced by mfix_initial_iterations().
void mfix_level::mfix_calc_drag_particle (int lev) protected
References calc_drag_particle(), construct_gradp(), and set_gradp_bcs().
Referenced by Evolve().
void mfix_level::mfix_calc_mflux (int lev) protected
References calc_mflux().
void mfix_level::mfix_calc_trd_and_tau (int lev) protected
References calc_tau_g(), and calc_trd_g().
void mfix_level::mfix_calc_volume_fraction (int lev, Real & sum_vol) protected
Referenced by Evolve(), mfix_init_fluid(), and PostInit().
void mfix_level::mfix_conv_rop (int lev) protected
References conv_rop().
void mfix_level::mfix_correct_0 (int lev) protected
References correct_p_0(), correct_u_0(), correct_v_0(), and correct_w_0().
void mfix_level::mfix_init_fluid (int lev, int is_restarting, Real dt, Real stop_time, int steady_state) protected
References init_fluid(), init_fluid_restart(), mfix_calc_volume_fraction(), mfix_initial_iterations(), mfix_project_velocity(), mfix_set_bc0(), mfix_set_p0(), mfix_set_projection_bcs(), and zero_wall_norm_vel().
Referenced by PostInit().
void mfix_level::mfix_initial_iterations (int lev, Real dt, Real stop_time, int steady_state) protected
References mfix_calc_drag_fluid().
Referenced by mfix_init_fluid().
void mfix_level::mfix_project_velocity (int lev) protected
Referenced by mfix_init_fluid().
void mfix_level::mfix_set_bc0 (int lev) protected
References set_bc0().
Referenced by mfix_init_fluid(), and Regrid().
void mfix_level::mfix_set_p0 (int lev) protected
References set_delp_dir(), and set_p0().
Referenced by mfix_init_fluid(), and Regrid().
void mfix_level::mfix_set_projection_bcs (int lev) protected
References set_projection_bcs().
Referenced by mfix_init_fluid().
void mfix_level::mfix_set_velocity_bcs (int lev) protected
References set_mac_velocity_bcs().
Referenced by mfix_calc_drag_fluid().
void mfix_level::mfix_solve_for_pp (int lev, Real dt, Real & num_p, Real & denom_p) protected
References mfix_solve_linear_equation(), and solve_pp_g().
void mfix_level::mfix_solve_for_u (int lev, Real dt, Real & num_u, Real & denom_u) protected
References mfix_solve_linear_equation(), and solve_u_g_star().
void mfix_level::mfix_solve_for_v (int lev, Real dt, Real & num_v, Real & denom_v) protected
References mfix_solve_linear_equation(), and solve_v_g_star().
void mfix_level::mfix_solve_for_w (int lev, Real dt, Real & num_w, Real & denom_w) protected
References mfix_solve_linear_equation(), and solve_w_g_star().
void mfix_level::mfix_solve_linear_equation (int eq_id, int lev, MultiFab & sol, MultiFab & matrix, MultiFab & rhs) protected
References get_solver_params(), and solve_bicgstab().
Referenced by mfix_solve_for_pp(), mfix_solve_for_u(), mfix_solve_for_v(), and mfix_solve_for_w().
void mfix_level::output (int lev, int estatus, int finish, int nstep, Real dt, Real time) inline
Referenced by collect_fluid(), init_namelist_module::init_namelist(), main(), output_manager_module::output_manager(), read_namelist_module::read_namelist(), and write_fluid().
void mfix_level::PostInit (int lev, Real dt, Real time, int nstep, int restart_flag, Real stop_time, int steady_state)
References init_collision(), mfix_calc_volume_fraction(), mfix_init_fluid(), and mfix_usr0().
Referenced by main().
void mfix_level::Regrid (int lev, int nstep)
References mfix_set_bc0(), mfix_set_p0(), and RegridArrays().
Referenced by main().
void mfix_level::RegridArrays (int lev, BoxArray & new_grids, DistributionMapping & new_dmap) protected
Referenced by Regrid().
virtual void mfix_level::RemakeLevel (int lev, amrex::Real time, const amrex::BoxArray & ba, const amrex::DistributionMapping & dm) inline override protected virtual
Remake an existing level using provided BoxArray and DistributionMapping and fill with existing fine and coarse data. Called by AmrCore::regrid.
void mfix_level::ResizeArrays ()
References legacy__eb_collisions.
Referenced by main().
void mfix_level::Restart (std::string & restart_chkfile, int * nstep, Real * dt, Real * time, IntVect & Nrep)
References AllocateArrays(), levelset__eb_pad, levelset__eb_refinement, levelset__pad, levelset__refinement, levelset__restart, and make_eb_geometry().
Referenced by main().
int mfix_level::solve_bicgstab (MultiFab & sol, const MultiFab & rhs, const MultiFab & matrix, int sweep_type, int precond_type, int maxiter, Real eps_rel, int lev) protected
References leq_matvec(), leq_msolve1(), leq_residual(), leq_scale(), and sxay().
Referenced by mfix_solve_linear_equation().
void mfix_level::usr3 (int lev)
References mfix_usr3().
Referenced by main().
void mfix_level::WriteCheckPointFile (std::string & check_file_name, int nstep = 0, Real dt = 0.0, Real time = 0.0) const
Referenced by main().
void mfix_level::WriteEBSurface (int lev)
References mfix_eb_grid_coverage(), mfix_eb_to_polygon(), mfix_write_eb_vtp(), and mfix_write_pvtp().
Referenced by main().
void mfix_level::WriteParticleAscii (std::string & par_ascii_file_name, int nstep = 0) const
Referenced by main().
void mfix_level::WritePlotFile (std::string & plot_file_name, int nstep = 0, Real dt = 0.0, Real time = 0.0) const
Referenced by main().
void mfix_level::WriteUSER (int lev, Real dt, Real time) const
References mfix_collect_fluid(), and mfix_write_fluid().
Referenced by main().
Member Data Documentation
bool mfix_level::legacy__eb_collisions = false
Referenced by InitParams(), and ResizeArrays().
int mfix_level::levelset__eb_pad = 2
Referenced by Init(), InitParams(), and Restart().
int mfix_level::levelset__eb_refinement = 1
Referenced by Init(), InitParams(), and Restart().
int mfix_level::levelset__pad = 2
Referenced by Init(), InitParams(), and Restart().
int mfix_level::levelset__refinement = 1
Parameters describing the level-set grid:
Referenced by Init(), InitParams(), and Restart().
bool mfix_level::levelset__restart = false
Referenced by main(), and Restart().
The documentation for this class was generated from the following files:
mfix/src/mfix_level.H
mfix/src/mfix_arrays.cpp
mfix/src/mfix_evolve.cpp
mfix/src/mfix_init.cpp
mfix/src/mfix_level.cpp
mfix/src/mfix_regrid.cpp
mfix/src/eb/get_walls.cpp
mfix/src/eb/mfix_eb.cpp
mfix/src/eb/mfix_eb_box.cpp
mfix/src/eb/mfix_eb_cyclone.cpp
mfix/src/eb/mfix_eb_cylinder.cpp
mfix/src/eb/mfix_eb_general.cpp
mfix/src/eb/mfix_eb_gshop.cpp
mfix/src/eb/mfix_eb_hopper.cpp
mfix/src/eb/mfix_eb_regular.cpp
mfix/src/eb/writeEBsurface.cpp
mfix/src/io/mfixIO.cpp
mfix/src/projection/compute_dt.cpp
mfix/src/projection/mfix_projection.cpp
mfix/src/simple/mfix_linear_solve.cpp
mfix/src/simple/mfix_simple.cpp
mfix/src/simple/solve_bicgstab.cpp