MFiX-Exa: avg_functions Module Reference
avg_functions Module Reference
Public Member Functions
real(rt) function avg (Xm, Xp)
real(rt) function avg_h (Xm, Xp)
Member Function/Subroutine Documentation
real(rt) function avg_functions::avg (double precision, intent(in) Xm, double precision, intent(in) Xp)
Referenced by calc_tau_u_g_module::calc_tau_u_g(), calc_tau_v_g_module::calc_tau_v_g(), calc_tau_w_g_module::calc_tau_w_g(), and convection_mod::compute_ugradu_z().
real(rt) function avg_functions::avg_h (double precision, intent(in) Xm, double precision, intent(in) Xp)
Referenced by calc_tau_u_g_module::calc_tau_u_g(), calc_tau_v_g_module::calc_tau_v_g(), calc_tau_w_g_module::calc_tau_w_g(), u_g_conv_dif::conv_dif_u_g(), v_g_conv_dif::conv_dif_v_g(), and w_g_conv_dif::conv_dif_w_g().
The documentation for this module was generated from the following file:
mfix/src/simple/functions_mod.f90