MFiX-Exa: check_point_sources_module Module Reference
check_point_sources_module Module Reference
Public Member Functions
subroutine, public check_point_sources (dx, dy, dz)
subroutine check_ps_geometry (dx, dy, dz)
subroutine check_ps_gas_phase (PSV)
subroutine check_ps_overflow (PSV)
Member Function/Subroutine Documentation
subroutine, public check_point_sources_module::check_point_sources (real(c_real), intent(in) dx, real(c_real), intent(in) dy, real(c_real), intent(in) dz)
References check_ps_gas_phase(), check_ps_geometry(), check_ps_overflow(), error_manager::finl_err_msg(), error_manager::init_err_msg(), and ps::ps_defined().
subroutine check_point_sources_module::check_ps_gas_phase (integer, intent(in) PSV)
References param::equal(), error_manager::finl_err_msg(), error_manager::flush_err_msg(), error_manager::init_err_msg(), and error_manager::ivar().
Referenced by check_point_sources().
subroutine check_point_sources_module::check_ps_geometry (real(c_real), intent(in) dx, real(c_real), intent(in) dy, real(c_real), intent(in) dz)
References calc_cell_module::calc_cell_ps(), error_manager::finl_err_msg(), error_manager::flush_err_msg(), error_manager::init_err_msg(), and ps::ps_defined().
Referenced by check_point_sources().
subroutine check_point_sources_module::check_ps_overflow (integer, intent(in) PSV)
References error_manager::finl_err_msg(), error_manager::flush_err_msg(), error_manager::init_err_msg(), and error_manager::ivar().
Referenced by check_point_sources().
The documentation for this module was generated from the following file:
mfix/src/check_data/check_point_sources.f90