MFiX-Exa: discretelement Module Reference
discretelement Module Reference
Public Member Functions
real(c_real) function, dimension(3) des_crossprdct (XX, YY)
Public Attributes
integer particle_types = 0
logical des_continuum_coupled
logical des_explicitly_coupled
logical des_oneway_coupled
character(len=64) des_coll_model
integer, parameter invalid_coll =-1
integer, parameter hertzian =0
integer, parameter lsd =1
integer des_coll_model_enum = invalid_coll
real(c_real) dtsolid
real(c_real) kn
real(c_real) kn_w
real(c_real) kt
real(c_real) kt_w
real(c_real) kt_fac
real(c_real) kt_w_fac
real(c_real) eta_des_n
real(c_real) eta_n_w
real(c_real) eta_des_t
real(c_real) eta_t_w
real(c_real) des_etat_fac
real(c_real) des_etat_w_fac
real(c_real), dimension(dim_m,
dim_m) des_etan
real(c_real), dimension(dim_m) des_etan_wall
real(c_real), dimension(dim_m,
dim_m) des_etat
real(c_real), dimension(dim_m) des_etat_wall
real(c_real) mew
real(c_real) mew_w
real(c_real), dimension(dim_m+dim_m
*(dim_m-1)/2) des_en_input
real(c_real), dimension(dim_m+dim_m
*(dim_m-1)/2) des_et_input
real(c_real), dimension(dim_m) des_en_wall_input
real(c_real), dimension(dim_m) des_et_wall_input
real(c_real), dimension(dim_m) e_young
real(c_real) ew_young
real(c_real), dimension(dim_m) v_poisson
real(c_real) vw_poisson
real(c_real), dimension(dim_m,
dim_m) hert_kn
real(c_real), dimension(dim_m) hert_kwn
real(c_real), dimension(dim_m,
dim_m) hert_kt
real(c_real), dimension(dim_m) hert_kwt
Member Function/Subroutine Documentation
real(c_real) function, dimension(3) discretelement::des_crossprdct (real(c_real), dimension(3), intent(in) XX, real(c_real), dimension(3), intent(in) YY)
Referenced by calc_collision_wall::calc_dem_force_with_wall_stl(), calc_force_dem_module::calc_force_dem(), calc_force_dem_module::calc_force_dem_nl(), cffctowall_module::cffctowall(), cfrelvel_module::cfrelvel(), and calc_collision_wall::cfrelvel_wall().
Member Data Documentation
character(len=64) discretelement::des_coll_model
integer discretelement::des_coll_model_enum = invalid_coll
logical discretelement::des_continuum_coupled
real(c_real), dimension(dim_m+dim_m*(dim_m-1)/2) discretelement::des_en_input
real(c_real), dimension(dim_m) discretelement::des_en_wall_input
real(c_real), dimension(dim_m+dim_m*(dim_m-1)/2) discretelement::des_et_input
real(c_real), dimension(dim_m) discretelement::des_et_wall_input
real(c_real), dimension(dim_m, dim_m) discretelement::des_etan
real(c_real), dimension(dim_m) discretelement::des_etan_wall
real(c_real), dimension(dim_m, dim_m) discretelement::des_etat
real(c_real) discretelement::des_etat_fac
real(c_real) discretelement::des_etat_w_fac
real(c_real), dimension(dim_m) discretelement::des_etat_wall
logical discretelement::des_explicitly_coupled
logical discretelement::des_oneway_coupled
real(c_real) discretelement::dtsolid
real(c_real), dimension(dim_m) discretelement::e_young
real(c_real) discretelement::eta_des_n
real(c_real) discretelement::eta_des_t
real(c_real) discretelement::eta_n_w
real(c_real) discretelement::eta_t_w
real(c_real) discretelement::ew_young
real(c_real), dimension(dim_m, dim_m) discretelement::hert_kn
real(c_real), dimension(dim_m, dim_m) discretelement::hert_kt
real(c_real), dimension(dim_m) discretelement::hert_kwn
real(c_real), dimension(dim_m) discretelement::hert_kwt
integer, parameter discretelement::hertzian =0
integer, parameter discretelement::invalid_coll =-1
real(c_real) discretelement::kn
real(c_real) discretelement::kn_w
real(c_real) discretelement::kt
real(c_real) discretelement::kt_fac
real(c_real) discretelement::kt_w
real(c_real) discretelement::kt_w_fac
integer, parameter discretelement::lsd =1
real(c_real) discretelement::mew
real(c_real) discretelement::mew_w
integer discretelement::particle_types = 0
real(c_real), dimension(dim_m) discretelement::v_poisson
real(c_real) discretelement::vw_poisson
The documentation for this module was generated from the following file:
mfix/src/des/discretelement_mod.f90