MFiX-Exa: calc_cell_module Module Reference
calc_cell_module Module Reference
Public Member Functions
subroutine, public calc_cell_ic (dx, dy, dz, x_w, y_s, z_b, x_e, y_n, z_t, i_w, i_e, j_s, j_n, k_b, k_t)
subroutine, public calc_cell_bc_wall (domlo, domhi, xlength, ylength, zlength, dx, dy, dz, x_w, y_s, z_b, x_e, y_n, z_t, i_w, i_e, j_s, j_n, k_b, k_t)
subroutine, public calc_cell_bc_flow (xlength, ylength, zlength, dx, dy, dz, x_w, y_s, z_b, x_e, y_n, z_t, i_w, i_e, j_s, j_n, k_b, k_t)
subroutine, public calc_cell_ps (psv, dx, dy, dz, i_w, i_e, j_s, j_n, k_b, k_t)
Member Function/Subroutine Documentation
subroutine, public calc_cell_module::calc_cell_bc_flow (real(rt), intent(in) xlength, real(rt), intent(in) ylength, real(rt), intent(in) zlength, real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz, real(rt), intent(in) x_w, real(rt), intent(in) y_s, real(rt), intent(in) z_b, real(rt), intent(in) x_e, real(rt), intent(in) y_n, real(rt), intent(in) z_t, integer, intent(out) i_w, integer, intent(out) i_e, integer, intent(out) j_s, integer, intent(out) j_n, integer, intent(out) k_b, integer, intent(out) k_t)
Referenced by check_bc_geometry_module::check_bc_geometry_flow(), set_bc_type_module::set_bc_type(), set_bc_flow_module::solids_massflow_to_volflow(), and set_bc_flow_module::solids_volflow_to_velocity().
subroutine, public calc_cell_module::calc_cell_bc_wall (integer, dimension(3), intent(in) domlo, integer, dimension(3), intent(in) domhi, real(rt), intent(in) xlength, real(rt), intent(in) ylength, real(rt), intent(in) zlength, real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz, real(rt), intent(in) x_w, real(rt), intent(in) y_s, real(rt), intent(in) z_b, real(rt), intent(in) x_e, real(rt), intent(in) y_n, real(rt), intent(in) z_t, integer, intent(out) i_w, integer, intent(out) i_e, integer, intent(out) j_s, integer, intent(out) j_n, integer, intent(out) k_b, integer, intent(out) k_t)
Referenced by check_bc_geometry_module::check_bc_geometry_wall(), and set_bc_type_module::set_bc_type().
subroutine, public calc_cell_module::calc_cell_ic (real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz, real(rt), intent(in) x_w, real(rt), intent(in) y_s, real(rt), intent(in) z_b, real(rt), intent(in) x_e, real(rt), intent(in) y_n, real(rt), intent(in) z_t, integer, intent(out) i_w, integer, intent(out) i_e, integer, intent(out) j_s, integer, intent(out) j_n, integer, intent(out) k_b, integer, intent(out) k_t)
Referenced by check_initial_conditions_module::check_ic_geometry(), par_gen_module::particle_generator(), and init_fluid_module::set_ic().
subroutine, public calc_cell_module::calc_cell_ps (integer, intent(in) psv, real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz, integer, intent(out) i_w, integer, intent(out) i_e, integer, intent(out) j_s, integer, intent(out) j_n, integer, intent(out) k_b, integer, intent(out) k_t)
Referenced by check_point_sources_module::check_ps_geometry().
The documentation for this module was generated from the following file:
mfix/src/calc_cell.f90