MFiX-Exa: residual Module Reference
residual Module Reference
Public Member Functions
subroutine calc_resid_vel (dir, lo, hi, alo, ahi, v0lo, v0hi, v1lo, v1hi, v2lo, v2hi, vel, vels1, vels2, A_m, b_m, mask, num, den)
subroutine calc_resid_pp (alo, ahi, lo, hi, b_m, b_mmax, num, den)
Public Attributes
real(rt) tol_resid
real(rt) tol_diverge
real(rt) norm_g
integer, parameter nresid = 8
integer, parameter resid_p = 1
integer, parameter resid_u = 2
integer, parameter resid_v = 3
integer, parameter resid_w = 4
real(rt) sum5_resid
Member Function/Subroutine Documentation
subroutine residual::calc_resid_pp (integer, dimension(3), intent(in) alo, integer, dimension(3), intent(in) ahi, integer, dimension(3), intent(in) lo, integer, dimension(3), intent(in) hi, real(rt), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)) b_m, real(rt), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)) b_mmax, real(rt), intent(inout) num, real(rt), intent(inout) den)
Referenced by solve_pp_module::solve_pp_g().
subroutine residual::calc_resid_vel (integer, intent(in) dir, integer, dimension(3), intent(in) lo, integer, dimension(3), intent(in) hi, integer, dimension(3), intent(in) alo, integer, dimension(3), intent(in) ahi, integer, dimension(3), intent(in) v0lo, integer, dimension(3), intent(in) v0hi, integer, dimension(3), intent(in) v1lo, integer, dimension(3), intent(in) v1hi, integer, dimension(3), intent(in) v2lo, integer, dimension(3), intent(in) v2hi, real(rt), dimension (v0lo(1):v0hi(1),v0lo(2):v0hi(2),v0lo(3):v0hi(3)), intent(in) vel, real(rt), dimension (v1lo(1):v1hi(1),v1lo(2):v1hi(2),v1lo(3):v1hi(3)), intent(in) vels1, real(rt), dimension (v2lo(1):v2hi(1),v2lo(2):v2hi(2),v2lo(3):v2hi(3)), intent(in) vels2, real(rt), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3),-3:3) A_m, real(rt), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)) b_m, real(rt), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)) mask, real(rt), intent(out) num, real(rt), intent(out) den)
Referenced by solve_vel_star_module::solve_u_g_star(), solve_vel_star_module::solve_v_g_star(), and solve_vel_star_module::solve_w_g_star().
Member Data Documentation
real(rt) residual::norm_g
integer, parameter residual::nresid = 8
integer, parameter residual::resid_p = 1
integer, parameter residual::resid_u = 2
integer, parameter residual::resid_v = 3
integer, parameter residual::resid_w = 4
real(rt) residual::sum5_resid
real(rt) residual::tol_diverge
real(rt) residual::tol_resid
The documentation for this module was generated from the following file:
mfix/src/simple/residual_mod.f90