MFiX-Exa: adjust_a Module Reference
adjust_a Module Reference
Public Member Functions
subroutine adjust_a_u (slo, shi, alo, ahi, lo, hi, A_m, b_m, rop_g, dy, dz)
subroutine adjust_a_v (slo, shi, alo, ahi, lo, hi, A_m, b_m, rop_g, dx, dz)
subroutine adjust_a_w (slo, shi, alo, ahi, lo, hi, A_m, b_m, rop_g, dx, dy)
Member Function/Subroutine Documentation
subroutine adjust_a::adjust_a_u (integer(c_int), dimension(3), intent(in) slo, integer(c_int), dimension(3), intent(in) shi, integer(c_int), dimension(3), intent(in) alo, integer(c_int), dimension(3), intent(in) ahi, integer(c_int), dimension(3), intent(in) lo, integer(c_int), dimension(3), intent(in) hi, real(c_real), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3), -3:3), intent(inout) A_m, real(c_real), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)), intent(inout) b_m, real(c_real), dimension(slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) rop_g, real(c_real), intent(in) dy, real(c_real), intent(in) dz)
Referenced by solve_vel_star_module::solve_u_g_star().
subroutine adjust_a::adjust_a_v (integer(c_int), dimension(3), intent(in) slo, integer(c_int), dimension(3), intent(in) shi, integer(c_int), dimension(3), intent(in) alo, integer(c_int), dimension(3), intent(in) ahi, integer(c_int), dimension(3), intent(in) lo, integer(c_int), dimension(3), intent(in) hi, real(c_real), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3), -3:3), intent(inout) A_m, real(c_real), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)), intent(inout) b_m, real(c_real), dimension(slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) rop_g, real(c_real), intent(in) dx, real(c_real), intent(in) dz)
Referenced by solve_vel_star_module::solve_v_g_star().
subroutine adjust_a::adjust_a_w (integer(c_int), dimension(3), intent(in) slo, integer(c_int), dimension(3), intent(in) shi, integer(c_int), dimension(3), intent(in) alo, integer(c_int), dimension(3), intent(in) ahi, integer(c_int), dimension(3), intent(in) lo, integer(c_int), dimension(3), intent(in) hi, real(c_real), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3), -3:3), intent(inout) A_m, real(c_real), dimension (alo(1):ahi(1),alo(2):ahi(2),alo(3):ahi(3)), intent(inout) b_m, real(c_real), dimension(slo(1):shi(1),slo(2):shi(2),slo(3):shi(3)), intent(in) rop_g, real(c_real), intent(in) dx, real(c_real), intent(in) dy)
Referenced by solve_vel_star_module::solve_w_g_star().
The documentation for this module was generated from the following file:
mfix/src/adjust_a_g.f90