MFiX-Exa: check_bc_geometry_module Module Reference
check_bc_geometry_module Module Reference
Public Member Functions
subroutine check_bc_geometry
subroutine check_bc_geometry_wall (bcv, dx, dy, dz, xlength, ylength, zlength, domlo, domhi)
subroutine check_bc_geometry_flow (bcv, dx, dy, dz, xlength, ylength, zlength, domlo, domhi)
Member Function/Subroutine Documentation
subroutine check_bc_geometry_module::check_bc_geometry ()
References error_manager::finl_err_msg(), error_manager::flush_err_msg(), error_manager::init_err_msg(), and error_manager::ivar().
Referenced by check_boundary_conditions_module::check_boundary_conditions().
subroutine check_bc_geometry_module::check_bc_geometry_flow (integer, intent(in) bcv, real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz, real(rt), intent(in) xlength, real(rt), intent(in) ylength, real(rt), intent(in) zlength, integer(c_int), dimension(3), intent(in) domlo, integer(c_int), dimension(3), intent(in) domhi)
References calc_cell_module::calc_cell_bc_flow(), error_manager::finl_err_msg(), error_manager::flush_err_msg(), and error_manager::init_err_msg().
Referenced by check_boundary_conditions_module::check_boundary_conditions().
subroutine check_bc_geometry_module::check_bc_geometry_wall (integer, intent(in) bcv, real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz, real(rt), intent(in) xlength, real(rt), intent(in) ylength, real(rt), intent(in) zlength, integer(c_int), dimension(3), intent(in) domlo, integer(c_int), dimension(3), intent(in) domhi)
References calc_cell_module::calc_cell_bc_wall(), error_manager::finl_err_msg(), error_manager::flush_err_msg(), and error_manager::init_err_msg().
Referenced by check_boundary_conditions_module::check_boundary_conditions().
The documentation for this module was generated from the following file:
mfix/src/check_data/check_bc_geometry.f90