MFiX-Exa: error_manager::ival Interface Reference
error_manager::ival Interface Reference
Public Member Functions
character(len=32) function ival_int (VAL)
character(len=32) function ival_dbl (VAL)
character(len=32) function ival_log (VAL)
Member Function/Subroutine Documentation
character(len=32) function error_manager::ival::ival_dbl (real(c_real), intent(in) VAL)
Referenced by error_manager::ival_dbl().
character(len=32) function error_manager::ival::ival_int (integer, intent(in) VAL)
Referenced by error_manager::ival_int().
character(len=32) function error_manager::ival::ival_log (logical, intent(in) VAL)
Referenced by error_manager::ival_log().
The documentation for this interface was generated from the following file:
mfix/src/error_manager_mod.f90