MFiX-Exa: mfix/src/des/mfix_des_K.H File Reference
mfix_des_K.H File Reference
#include "mfix_pc.H"
Functions
AMREX_GPU_HOST_DEVICE AMREX_INLINE void cross_product (const amrex::RealVect &a, const amrex::RealVect &b, amrex::RealVect &c)
AMREX_GPU_HOST_DEVICE AMREX_INLINE amrex::Real dot_product (const amrex::RealVect &a, const amrex::RealVect &b)
AMREX_GPU_HOST_DEVICE AMREX_INLINE void cfrelvel (const MFIXParticleContainer::ParticleType &p1, const MFIXParticleContainer::ParticleType &p2, amrex::Real &vrn, amrex::RealVect &vslip, const amrex::RealVect &normal, const amrex::Real dist_mag)
AMREX_GPU_HOST_DEVICE AMREX_INLINE amrex::Real interp_level_set (MFIXParticleContainer::ParticleType const &p, const int n_refine, amrex::Array4< amrex::Real const > const &phi, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const &plo, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const &dxi)
AMREX_GPU_HOST_DEVICE AMREX_INLINE void level_set_normal (MFIXParticleContainer::ParticleType const &p, const int n_refine, amrex::RealVect &normal, amrex::Array4< amrex::Real const > const &phi, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const &plo, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const &dxi)
Function Documentation
AMREX_GPU_HOST_DEVICE AMREX_INLINE void cfrelvel (const MFIXParticleContainer::ParticleType & p1, const MFIXParticleContainer::ParticleType & p2, amrex::Real & vrn, amrex::RealVect & vslip, const amrex::RealVect & normal, const amrex::Real dist_mag)
References cross_product(), dot_product(), realData::omegax, realData::omegay, realData::omegaz, realData::radius, realData::velx, realData::vely, and realData::velz.
Referenced by MFIXParticleContainer::EvolveParticles().
AMREX_GPU_HOST_DEVICE AMREX_INLINE void cross_product (const amrex::RealVect & a, const amrex::RealVect & b, amrex::RealVect & c)
Referenced by cfrelvel(), and MFIXParticleContainer::EvolveParticles().
AMREX_GPU_HOST_DEVICE AMREX_INLINE amrex::Real dot_product (const amrex::RealVect & a, const amrex::RealVect & b)
Referenced by cfrelvel(), MFIXParticleContainer::EvolveParticles(), level_set_normal(), and mfix::mfix_calc_transfer_coeffs().
AMREX_GPU_HOST_DEVICE AMREX_INLINE amrex::Real interp_level_set (MFIXParticleContainer::ParticleType const & p, const int n_refine, amrex::Array4< amrex::Real const > const & phi, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const & plo, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const & dxi)
Referenced by MFIXParticleContainer::EvolveParticles().
AMREX_GPU_HOST_DEVICE AMREX_INLINE void level_set_normal (MFIXParticleContainer::ParticleType const & p, const int n_refine, amrex::RealVect & normal, amrex::Array4< amrex::Real const > const & phi, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const & plo, amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > const & dxi)
References dot_product().
Referenced by MFIXParticleContainer::EvolveParticles().