MFiX-Exa: mfix/src/eb/mfix_eb_F.H File Reference
mfix_eb_F.H File Reference
#include <AMReX_REAL.H>
#include <AMReX_BLFort.H>
#include <AMReX_SPACE.H>
Typedefs
typedef double amrex_particle_real
Functions
void mfix_get_walls (int *bcv, int *exists, void *normal, void *center)
void mfix_eb_to_polygon (const amrex::Real *dx, const int *slo, const int *shi, const void *flag, const int *fglo, const int *fghi, const amrex_real *bcent, const int *blo, const int *bhi, const amrex_real *ax, const int *axlo, const int *axhi, const amrex_real *ay, const int *aylo, const int *ayhi, const amrex_real *az, const int *azlo, const int *azhi)
void mfix_write_eb_vtp (int *myID)
void mfix_write_pvtp (int *nProcs)
void mfix_eb_grid_coverage (int *myID, const amrex::Real *dx, const int *slo, const int *shi, const void *flag, const int *fglo, const int *fghi)
void calc_wall_collisions_ls (void *rparticles, const int *ntot, const int *nrp, amrex_real *tow, amrex_real *fc, amrex_real *subdt, const int *valid, const int *vlo, const int *vhi, const amrex_real *phi, const int *phlo, const int *phhi, const amrex_real *dx, const int *n_refine)
Typedef Documentation
typedef double amrex_particle_real
Function Documentation
void calc_wall_collisions_ls (void * rparticles, const int * ntot, const int * nrp, amrex_real * tow, amrex_real * fc, amrex_real * subdt, const int * valid, const int * vlo, const int * vhi, const amrex_real * phi, const int * phlo, const int * phhi, const amrex_real * dx, const int * n_refine)
void mfix_eb_grid_coverage (int * myID, const amrex::Real * dx, const int * slo, const int * shi, const void * flag, const int * fglo, const int * fghi)
Referenced by mfix_level::WriteEBSurface().
void mfix_eb_to_polygon (const amrex::Real * dx, const int * slo, const int * shi, const void * flag, const int * fglo, const int * fghi, const amrex_real * bcent, const int * blo, const int * bhi, const amrex_real * ax, const int * axlo, const int * axhi, const amrex_real * ay, const int * aylo, const int * ayhi, const amrex_real * az, const int * azlo, const int * azhi)
Referenced by mfix_level::WriteEBSurface().
void mfix_get_walls (int * bcv, int * exists, void * normal, void * center)
void mfix_write_eb_vtp (int * myID)
Referenced by mfix_level::WriteEBSurface().
void mfix_write_pvtp (int * nProcs)
Referenced by mfix_level::WriteEBSurface().