MFiX-Exa: discretelement Module Reference
discretelement Module Reference
Functions/Subroutines
real(rt) function, dimension(3) des_crossprdct (XX, YY)
Variables
real(rt) dtsolid
real(rt) kn
real(rt) kn_w
real(rt) kt
real(rt) kt_w
real(rt) kt_fac
real(rt) kt_w_fac
real(rt) eta_des_n
real(rt) eta_n_w
real(rt) eta_des_t
real(rt) eta_t_w
real(rt) des_etat_fac
real(rt) des_etat_w_fac
real(rt), dimension(dim_m, dim_m) des_etan
real(rt), dimension(dim_m) des_etan_wall
real(rt), dimension(dim_m, dim_m) des_etat
real(rt), dimension(dim_m) des_etat_wall
real(rt) mew
real(rt) mew_w
real(rt), dimension(dim_m+dim_m *(dim_m-1)/2) des_en_input
real(rt), dimension(dim_m) des_en_wall_input
real(rt), dimension(dim_m) dp_max = -1.0d0
real(rt), dimension(dim_m) dp_min = -1.0d0
real(rt), dimension(dim_m) dp_avg = -1.0d0
real(rt), dimension(dim_m) ro_max = -1.0d0
real(rt), dimension(dim_m) ro_min = -1.0d0
real(rt), dimension(dim_m) ro_avg = -1.0d0
Function/Subroutine Documentation
real(rt) function, dimension(3) discretelement::des_crossprdct (real(rt), dimension(3), intent(in) XX, real(rt), dimension(3), intent(in) YY)
Referenced by calc_particle_collisions(), and cfrelvel_module::cfrelvel().
Variable Documentation
real(rt), dimension(dim_m+dim_m*(dim_m-1)/2) discretelement::des_en_input
Referenced by init_collision_lsd(), and set_lsd_collision_coefficients().
real(rt), dimension(dim_m) discretelement::des_en_wall_input
Referenced by init_collision_lsd(), and set_lsd_collision_coefficients().
real(rt), dimension(dim_m, dim_m) discretelement::des_etan
Referenced by calc_particle_collisions(), init_collision(), and init_collision_lsd().
real(rt), dimension(dim_m) discretelement::des_etan_wall
Referenced by init_collision(), and init_collision_lsd().
real(rt), dimension(dim_m, dim_m) discretelement::des_etat
Referenced by calc_particle_collisions(), init_collision(), and init_collision_lsd().
real(rt) discretelement::des_etat_fac
Referenced by init_collision_lsd(), and set_lsd_collision_coefficients().
real(rt) discretelement::des_etat_w_fac
Referenced by init_collision_lsd(), and set_lsd_collision_coefficients().
real(rt), dimension(dim_m) discretelement::des_etat_wall
Referenced by init_collision(), and init_collision_lsd().
real(rt), dimension(dim_m) discretelement::dp_avg = -1.0d0
Referenced by init_collision().
real(rt), dimension(dim_m) discretelement::dp_max = -1.0d0
Referenced by init_collision().
real(rt), dimension(dim_m) discretelement::dp_min = -1.0d0
Referenced by init_collision(), and ParticlesGenerator::uni_rno().
real(rt) discretelement::dtsolid
Referenced by init_collision_lsd().
real(rt) discretelement::eta_des_n
real(rt) discretelement::eta_des_t
real(rt) discretelement::eta_n_w
real(rt) discretelement::eta_t_w
real(rt) discretelement::kn
Referenced by calc_particle_collisions(), MFIXParticleContainer::EvolveParticles(), init_collision_lsd(), and set_lsd_collision_coefficients().
real(rt) discretelement::kn_w
Referenced by MFIXParticleContainer::EvolveParticles(), init_collision_lsd(), and set_lsd_collision_coefficients().
real(rt) discretelement::kt
Referenced by calc_particle_collisions(), init_collision_lsd(), and set_lsd_collision_coefficients().
real(rt) discretelement::kt_fac
Referenced by init_collision_lsd(), and set_lsd_collision_coefficients().
real(rt) discretelement::kt_w
Referenced by init_collision_lsd(), and set_lsd_collision_coefficients().
real(rt) discretelement::kt_w_fac
Referenced by init_collision_lsd(), and set_lsd_collision_coefficients().
real(rt) discretelement::mew
Referenced by calc_particle_collisions(), MFIXParticleContainer::EvolveParticles(), and set_lsd_collision_coefficients().
real(rt) discretelement::mew_w
Referenced by MFIXParticleContainer::EvolveParticles(), and set_lsd_collision_coefficients().
real(rt), dimension(dim_m) discretelement::ro_avg = -1.0d0
Referenced by init_collision().
real(rt), dimension(dim_m) discretelement::ro_max = -1.0d0
Referenced by init_collision().
real(rt), dimension(dim_m) discretelement::ro_min = -1.0d0
Referenced by init_collision().