MFiX-Exa: read_namelist_module Module Reference
read_namelist_module Module Reference
Functions/Subroutines
subroutine read_namelist (mfix_dat)
subroutine add_argument (fname, nlen)
Function/Subroutine Documentation
subroutine read_namelist_module::add_argument (character(kind=c_char), dimension(nlen), intent(in) fname, integer(c_int), intent(in) nlen)
subroutine read_namelist_module::read_namelist (character(len=*), intent(in) mfix_dat)
References deprecated_or_unknown_module::deprecated_or_unknown(), error_manager::finl_err_msg(), error_manager::flush_err_msg(), error_manager::init_err_msg(), remove_comment_module::remove_comment(), remove_comment_module::remove_par_blanks(), and set_keyword().