MFiX-Exa: check_bc_walls_module Module Reference
check_bc_walls_module Module Reference
Functions/Subroutines
subroutine, public check_bc_walls (bcv)
Function/Subroutine Documentation
subroutine, public check_bc_walls_module::check_bc_walls (integer, intent(in) bcv)
References error_manager::err_msg, error_manager::finl_err_msg(), error_manager::flush_err_msg(), error_manager::init_err_msg(), and error_manager::ivar().
Referenced by check_boundary_conditions_module::check_boundary_conditions().