MFiX-Exa: error_manager Module Reference
error_manager Module Reference
Data Types
interface ival
Functions/Subroutines
subroutine init_error_manager
subroutine init_err_msg (CALLER)
subroutine finl_err_msg
subroutine flush_err_msg (DEBUG, HEADER, FOOTER, ABORT, LOG, CALL_TREE)
subroutine show_call_tree (HEADER, FOOTER)
character(len=32) function ivar (VAR, i1, i2, i3)
character(len=32) function ival_int (VAL)
character(len=32) function ival_dbl (VAL)
character(len=32) function ival_log (VAL)
Variables
integer, parameter line_count = 32
integer, parameter line_length = 256
character(len=line_length), dimension(line_count) err_msg
integer ier_em
Function/Subroutine Documentation
subroutine error_manager::finl_err_msg ()
References err_msg, and line_count.
Referenced by check_bc_inflow_module::check_bc_mass_inflow(), check_bc_outflow_module::check_bc_outflow(), check_bc_inflow_module::check_bc_p_inflow(), check_bc_outflow_module::check_bc_p_outflow(), check_bc_walls_module::check_bc_walls(), check_collision_model::check_collision_model_hertz(), check_collision_model::check_collision_model_lsd(), check_gas_prop_module::check_gas_properties(), check_initial_conditions_module::check_ic_common_discrete(), check_particle_prop_module::check_particle_properties(), check_point_sources_module::check_point_sources(), check_point_sources_module::check_ps_gas_phase(), check_point_sources_module::check_ps_geometry(), check_point_sources_module::check_ps_overflow(), check_run_control_module::check_run_control(), deprecated_or_unknown_module::deprecated_or_unknown(), drag_usr(), and read_namelist_module::read_namelist().
subroutine error_manager::flush_err_msg (logical, intent(in), optional DEBUG, logical, intent(in), optional HEADER, logical, intent(in), optional FOOTER, logical, intent(in), optional ABORT, logical, intent(in), optional LOG, logical, intent(in), optional CALL_TREE)
References err_msg, line_count, and line_length.
Referenced by check_bc_inflow_module::check_bc_mass_inflow(), check_bc_outflow_module::check_bc_outflow(), check_bc_inflow_module::check_bc_p_inflow(), check_bc_outflow_module::check_bc_p_outflow(), check_bc_walls_module::check_bc_walls(), check_collision_model::check_collision_model_hertz(), check_collision_model::check_collision_model_lsd(), check_gas_prop_module::check_gas_properties(), check_initial_conditions_module::check_ic_common_discrete(), check_particle_prop_module::check_particle_properties(), check_point_sources_module::check_ps_gas_phase(), check_point_sources_module::check_ps_geometry(), check_point_sources_module::check_ps_overflow(), check_run_control_module::check_run_control(), deprecated_or_unknown_module::deprecated_or_unknown(), drag_usr(), and read_namelist_module::read_namelist().
subroutine error_manager::init_err_msg (character(len=*), intent(in) CALLER)
References err_msg, and show_call_tree().
Referenced by check_bc_inflow_module::check_bc_mass_inflow(), check_bc_outflow_module::check_bc_outflow(), check_bc_inflow_module::check_bc_p_inflow(), check_bc_outflow_module::check_bc_p_outflow(), check_bc_walls_module::check_bc_walls(), check_collision_model::check_collision_model_hertz(), check_collision_model::check_collision_model_lsd(), check_gas_prop_module::check_gas_properties(), check_initial_conditions_module::check_ic_common_discrete(), check_particle_prop_module::check_particle_properties(), check_point_sources_module::check_point_sources(), check_point_sources_module::check_ps_gas_phase(), check_point_sources_module::check_ps_geometry(), check_point_sources_module::check_ps_overflow(), check_run_control_module::check_run_control(), deprecated_or_unknown_module::deprecated_or_unknown(), drag_usr(), and read_namelist_module::read_namelist().
subroutine error_manager::init_error_manager ()
References err_msg, and ier_em.
Referenced by check_inputs().
character(len=32) function error_manager::ival_dbl (real(rt), intent(in) VAL)
character(len=32) function error_manager::ival_int (integer, intent(in) VAL)
character(len=32) function error_manager::ival_log (logical, intent(in) VAL)
character(len=32) function error_manager::ivar (character(len=*), intent(in) VAR, integer, intent(in) i1, integer, intent(in), optional i2, integer, intent(in), optional i3)
Referenced by check_bc_geometry_module::check_bc_geometry(), check_bc_outflow_module::check_bc_outflow(), check_bc_outflow_module::check_bc_p_outflow(), check_bc_range(), check_bc_flow_module::check_bc_vel_inflow(), check_bc_flow_module::check_bc_vel_outflow(), check_bc_walls_module::check_bc_walls(), check_collision_model::check_collision_model_hertz(), check_collision_model::check_collision_model_lsd(), check_initial_conditions_module::check_ic_gas_phase(), check_initial_conditions_module::check_ic_overflow(), check_initial_conditions_module::check_ic_solids_phases(), check_point_sources_module::check_ps_gas_phase(), check_point_sources_module::check_ps_overflow(), check_run_control_module::check_run_control(), and drag_usr().
subroutine error_manager::show_call_tree (logical, intent(in), optional HEADER, logical, intent(in), optional FOOTER)
Referenced by init_err_msg().
Variable Documentation
character(len=line_length), dimension(line_count) error_manager::err_msg
Referenced by check_bc_geometry_module::check_bc_geometry(), check_bc_geometry_module::check_bc_geometry_flow(), check_bc_inflow_module::check_bc_mass_inflow(), check_bc_outflow_module::check_bc_outflow(), check_bc_inflow_module::check_bc_p_inflow(), check_bc_outflow_module::check_bc_p_outflow(), check_bc_range(), check_bc_flow_module::check_bc_vel_inflow(), check_bc_flow_module::check_bc_vel_outflow(), check_bc_walls_module::check_bc_walls(), check_collision_model::check_collision_model_hertz(), check_collision_model::check_collision_model_lsd(), check_gas_prop_module::check_gas_properties(), check_initial_conditions_module::check_ic_common_discrete(), check_initial_conditions_module::check_ic_gas_phase(), check_initial_conditions_module::check_ic_geometry(), check_initial_conditions_module::check_ic_overflow(), check_initial_conditions_module::check_ic_solids_phases(), check_particle_prop_module::check_particle_properties(), check_point_sources_module::check_ps_gas_phase(), check_point_sources_module::check_ps_geometry(), check_point_sources_module::check_ps_overflow(), check_run_control_module::check_run_control(), drag_usr(), finl_err_msg(), flush_err_msg(), init_err_msg(), and init_error_manager().
integer error_manager::ier_em
Referenced by init_error_manager().
integer, parameter error_manager::line_count = 32
Referenced by finl_err_msg(), and flush_err_msg().
integer, parameter error_manager::line_length = 256
Referenced by flush_err_msg().