MFiX-Exa: parse_line_module Module Reference
parse_line_module Module Reference
Functions/Subroutines
subroutine parse_line (LINE, LMAX, READ_FLAG)
subroutine parse_arith (LINE, LMAX)
Function/Subroutine Documentation
subroutine parse_line_module::parse_arith (character, dimension(*) LINE, integer LMAX)
Referenced by parse_line().
subroutine parse_line_module::parse_line (character(len=*), intent(in) LINE, integer, intent(in) LMAX, logical, intent(out) READ_FLAG)
References parse_arith().
Referenced by set_keyword().