MFiX-Exa: check_initial_conditions_module Module Reference
check_initial_conditions_module Module Reference
Functions/Subroutines
subroutine, public check_initial_conditions (dx, dy, dz, domlo, domhi)
subroutine check_ic_geometry (dx, dy, dz, domlo, domhi)
subroutine check_ic_gas_phase (ICV)
subroutine check_ic_solids_phases (ICV)
subroutine check_ic_overflow (ICV)
subroutine check_ic_common_discrete
Function/Subroutine Documentation
subroutine check_initial_conditions_module::check_ic_common_discrete ()
References error_manager::err_msg, error_manager::finl_err_msg(), error_manager::flush_err_msg(), and error_manager::init_err_msg().
Referenced by check_initial_conditions().
subroutine check_initial_conditions_module::check_ic_gas_phase (integer, intent(in) ICV)
References error_manager::err_msg, and error_manager::ivar().
Referenced by check_initial_conditions().
subroutine check_initial_conditions_module::check_ic_geometry (real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz, integer(c_int), dimension(3), intent(in) domlo, integer(c_int), dimension(3), intent(in) domhi)
References error_manager::err_msg.
Referenced by check_initial_conditions().
subroutine check_initial_conditions_module::check_ic_overflow (integer, intent(in) ICV)
References error_manager::err_msg, and error_manager::ivar().
Referenced by check_initial_conditions().
subroutine check_initial_conditions_module::check_ic_solids_phases (integer, intent(in) ICV)
References error_manager::err_msg, and error_manager::ivar().
Referenced by check_initial_conditions().
subroutine, public check_initial_conditions_module::check_initial_conditions (real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz, integer(c_int), dimension(3), intent(in) domlo, integer(c_int), dimension(3), intent(in) domhi)
References check_ic_common_discrete(), check_ic_gas_phase(), check_ic_geometry(), check_ic_overflow(), and check_ic_solids_phases().