MFiX-Exa: check_boundary_conditions_module Module Reference
check_boundary_conditions_module Module Reference
Functions/Subroutines
subroutine check_boundary_conditions (dx, dy, dz, xlength, ylength, zlength, domlo, domhi)
Function/Subroutine Documentation
subroutine check_boundary_conditions_module::check_boundary_conditions (real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz, real(rt), intent(in) xlength, real(rt), intent(in) ylength, real(rt), intent(in) zlength, integer(c_int), dimension(3), intent(in) domlo, integer(c_int), dimension(3), intent(in) domhi)
References check_bc_inflow_module::check_bc_mass_inflow(), check_bc_outflow_module::check_bc_outflow(), check_bc_inflow_module::check_bc_p_inflow(), check_bc_outflow_module::check_bc_p_outflow(), and check_bc_range().