MFiX-Exa: check_bc_geometry_module Module Reference
check_bc_geometry_module Module Reference
Functions/Subroutines
subroutine check_bc_geometry
subroutine check_bc_geometry_wall (bcv, dx, dy, dz, xlength, ylength, zlength, domlo, domhi)
subroutine check_bc_geometry_flow (bcv, dx, dy, dz, xlength, ylength, zlength, domlo, domhi)
Function/Subroutine Documentation
subroutine check_bc_geometry_module::check_bc_geometry ()
References error_manager::err_msg, and error_manager::ivar().
Referenced by check_boundary_conditions_module::check_boundary_conditions().
subroutine check_bc_geometry_module::check_bc_geometry_flow (integer, intent(in) bcv, real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz, real(rt), intent(in) xlength, real(rt), intent(in) ylength, real(rt), intent(in) zlength, integer(c_int), dimension(3), intent(in) domlo, integer(c_int), dimension(3), intent(in) domhi)
References error_manager::err_msg.
Referenced by check_boundary_conditions_module::check_boundary_conditions().
subroutine check_bc_geometry_module::check_bc_geometry_wall (integer, intent(in) bcv, real(rt), intent(in) dx, real(rt), intent(in) dy, real(rt), intent(in) dz, real(rt), intent(in) xlength, real(rt), intent(in) ylength, real(rt), intent(in) zlength, integer(c_int), dimension(3), intent(in) domlo, integer(c_int), dimension(3), intent(in) domhi)
Referenced by check_boundary_conditions_module::check_boundary_conditions().