MFiX-Exa: mfix/src/io/read_namelist.f90 File Reference
read_namelist.f90 File Reference
Modules
module read_namelist_module
Functions/Subroutines
subroutine read_namelist_module::read_namelist (mfix_dat)
subroutine set_keyword (ERROR)
subroutine read_namelist_module::add_argument (fname, nlen)
Function/Subroutine Documentation
subroutine read_namelist::set_keyword (logical, intent(out) ERROR)
References parse_line_module::parse_line(), and remove_comment_module::remove_par_blanks().
Referenced by read_namelist_module::read_namelist().