MFiX-Exa: mfix/src/usr/usr_drag.f90 File Reference
usr_drag.f90 File Reference
Functions/Subroutines
subroutine drag_usr (I, J, K, M_NP, lDgA, EPg, Mug, ROg, VREL, DPM, ROs, lUg, lVg, lWg)
Function/Subroutine Documentation
subroutine drag_usr (integer, intent(in) I, integer, intent(in) J, integer, intent(in) K, integer, intent(in) M_NP, real(rt), intent(out) lDgA, real(rt), intent(in) EPg, real(rt), intent(in) Mug, real(rt), intent(in) ROg, real(rt), intent(in) VREL, real(rt), intent(in) DPM, real(rt), intent(in) ROs, real(rt), intent(in) lUg, real(rt), intent(in) lVg, real(rt), intent(in) lWg)
References error_manager::err_msg, error_manager::finl_err_msg(), error_manager::flush_err_msg(), error_manager::init_err_msg(), and error_manager::ivar().